export default {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  coverageProvider: "v8",
  moduleNameMapper: {
    "\\.(css|less|scss|sass)$": "<rootDir>/__mocks__/styleMock.js",
    "\\.(gif|ttf|eot|svg|png)$": "<rootDir>/__mocks__/fileMock.js",
  },
  setupFilesAfterEnv: ["<rootDir>/src/setupTests.ts"],
  collectCoverageFrom: [
    "<rootDir>/src/game/**/*.{ts,tsx}",
    "<rootDir>/src/store/**/*.{ts,tsx}",
    "<rootDir>/src/utils/**/*.{ts,tsx}",
    "!<rootDir>/src/content/**/*",
    "!<rootDir>/src/game/scenes/**/*",
    "!<rootDir>/src/game/objects/**/*",
    "!<rootDir>/src/game/utils/IsoObjectFactory.ts",
    "!<rootDir>/src/game/services/**/*",
    "!<rootDir>/src/game/systems/surveillance/**/*",
    "!<rootDir>/src/game/systems/curfewStateMachine.ts",
    "!<rootDir>/src/game/narrative/**/*",
    "!<rootDir>/src/game/ai/**/*",
    "!<rootDir>/src/game/combat/enemyAI.ts",
    "!<rootDir>/src/game/combat/automation/autoBattlePlanner.ts",
    "!<rootDir>/src/game/quests/storylets/**/*",
    "!<rootDir>/src/game/systems/georgeAssistant.ts",
    "!<rootDir>/src/game/systems/suspicion/**/*",
    "!<rootDir>/src/game/world/generation/**/*",
    "!<rootDir>/src/game/world/environment/environmentMatrix.ts",
    "!<rootDir>/src/game/utils/math.ts",
    "!<rootDir>/src/game/systems/perks.ts",
    "!<rootDir>/src/game/systems/stamina.ts",
    "!<rootDir>/src/game/inventory/encumbrance.ts",
    "!<rootDir>/src/game/systems/paranoia/stimuli.ts",
    "!<rootDir>/src/game/combat/automation/AutoBattleController.ts",
    "!<rootDir>/src/game/systems/missionProgression.ts",
    "!<rootDir>/src/game/world/dayNightCycle.ts",
    "!<rootDir>/src/components/**/*",
    "!<rootDir>/src/App.tsx",
    "!<rootDir>/src/game/**/types.ts",
    "!<rootDir>/src/game/interfaces/environment.ts",
    "!<rootDir>/src/game/interfaces/georgeAssistant.ts",
    "!<rootDir>/src/game/interfaces/missions.ts",
    "!<rootDir>/src/game/narrative/structureTypes.ts",
    "!<rootDir>/src/game/narrative/tripleTypes.ts",
    "!<rootDir>/src/game/narrative/tripleExtraction.ts",
    "!<rootDir>/src/game/narrative/dialogueTone/roleTemplateTypes.ts",
    "!<rootDir>/src/game/systems/suspicion/types.ts",
    "!<rootDir>/src/game/systems/suspicion/index.ts",
    "!<rootDir>/src/game/systems/reputation/witnessService.ts",
    "!<rootDir>/src/game/systems/reputation/events.ts",
    "!<rootDir>/src/store/index.ts",
    "!<rootDir>/src/store/paranoiaSlice.ts",
    "!<rootDir>/src/store/storyletSlice.ts",
    "!<rootDir>/src/store/selectors/reputationSelectors.ts",
  ],
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "<rootDir>/src/components/",
    "/src/App.tsx$",
    "<rootDir>/src/content/",
    "<rootDir>/src/game/.*/types\\.ts$",
    "<rootDir>/src/game/interfaces/environment\\.ts$",
    "<rootDir>/src/game/interfaces/georgeAssistant\\.ts$",
    "<rootDir>/src/game/interfaces/missions\\.ts$",
    "<rootDir>/src/game/narrative/structureTypes\\.ts$",
    "<rootDir>/src/game/narrative/tripleTypes\\.ts$",
    "<rootDir>/src/game/narrative/tripleExtraction\\.ts$",
    "<rootDir>/src/game/narrative/dialogueTone/roleTemplateTypes\\.ts$",
    "<rootDir>/src/game/systems/suspicion/types\\.ts$",
    "<rootDir>/src/game/systems/suspicion/index\\.ts$",
    "<rootDir>/src/game/narrative/.*",
    "<rootDir>/src/game/ai/.*",
    "<rootDir>/src/game/combat/enemyAI\\.ts$",
    "<rootDir>/src/game/quests/storylets/.*",
    "<rootDir>/src/game/systems/georgeAssistant\\.ts$",
    "<rootDir>/src/game/systems/suspicion/.*",
    "<rootDir>/src/game/world/generation/.*",
    "<rootDir>/src/game/world/environment/environmentMatrix\\.ts$",
    "<rootDir>/src/game/utils/math\\.ts$",
    "<rootDir>/src/game/systems/perks\\.ts$",
    "<rootDir>/src/game/systems/stamina\\.ts$",
    "<rootDir>/src/game/inventory/encumbrance\\.ts$",
    "<rootDir>/src/game/systems/reputation/witnessService\\.ts$",
    "<rootDir>/src/game/systems/reputation/events\\.ts$",
    "<rootDir>/src/game/combat/automation/autoBattlePlanner\\.ts$",
    "<rootDir>/src/store/index\\.ts$",
    "<rootDir>/src/store/paranoiaSlice\\.ts$",
    "<rootDir>/src/store/storyletSlice\\.ts$",
    "<rootDir>/src/store/selectors/reputationSelectors\\.ts$",
  ],
  coverageReporters: ["text", "text-summary", "lcov", "json-summary"],
  coverageThreshold: {
    global: {
      statements: 70,
      branches: 65,
      functions: 70,
      lines: 70,
    },
  },
};
