import { topicIdsForChapter } from './coverage';
import { GAME_BIBLE_DECISION_COVERAGE } from './traceability';
import {
  defineGameBibleChapter,
  type GameBibleChapter,
  type GameBibleChapterDraft,
} from './types';
import { GAME_BIBLE_SHARED_RULES as rules } from './sharedRules';

const source = (name: string) => `memory-bank/01 MVP/${name}.md`;

const chapterTopics = (chapterId: string): [string[], string[], string[], string[], string[]] => {
  const result: [string[], string[], string[], string[], string[]] = [[], [], [], [], []];
  topicIdsForChapter(chapterId).forEach((topicId, index) => result[index % result.length].push(topicId));
  return result;
};

const chapterDecisions = (chapterId: string): string[] =>
  Object.entries(GAME_BIBLE_DECISION_COVERAGE)
    .filter(([, sectionIds]) => sectionIds.some((sectionId) => sectionId.startsWith(`${chapterId}.`)))
    .map(([decisionId]) => decisionId);

const chapter = (
  draft: Omit<GameBibleChapterDraft, 'topicIdsBySection' | 'decisionRefs'>
): GameBibleChapter => defineGameBibleChapter({
  ...draft,
  topicIdsBySection: chapterTopics(draft.id),
  decisionRefs: chapterDecisions(draft.id),
});

export const EN_GAME_BIBLE_CHAPTERS: GameBibleChapter[] = [
  chapter({
    id: 'identity',
    group: 'FOUNDATION',
    title: 'What The Getaway Is',
    summary: 'A surveillance RPG about leaving a city that works. One person, one night, one district under institutional pressure — and a system that only becomes dangerous when you break its rules where it can see you.',
    keywords: ['surveillance-rpg', 'design pillars', 'escape', 'grounded dystopia', 'what kind of game'],
    sourceRefs: [source('Game Design'), source('10 MVP Spine')],
    relatedChapterIds: ['setting', 'journey', 'condition', 'boundaries'],
    copy: {
      overviewTitle: 'The fantasy and the promise',
      overviewText: 'The Getaway is a game about leaving. Tokyo, 2036. The city is clean, convenient, and watched. You are an American expatriate with a missing father, a private AI named George, and a plan to get to Miami. Nobody is hunting you when the game begins — that is the point. Every camera treats you as one more commuter until you break a rule in front of it. The game is the distance between being ordinary and being evidence, and how carefully you cross it.',
      principleTitle: 'No power fantasy',
      principleBody: 'You never become stronger than the system. You become harder to attribute. Preparation, timing, reading people, and knowing when to walk away are the whole arsenal. There is no weapon to find, and shooting your way out is not a fallback — it does not exist.',
      flowTitle: 'The shape of a run',
      flowSteps: [
        'Choose an authored civilian cover, then learn exactly which binary abilities it carries.',
        'Take a bargain from Lira that is humane and concrete — medicine for passage.',
        'Prepare as much or as little as you want. Two contacts can sharpen the picture; neither is required.',
        'Cross a watched district where every escalation traces back to something a camera actually saw.',
        'Deliver, validate, debrief. Leave with a record of what really happened — not a score.',
      ],
      exampleText: 'A good run is a chain of judged risks, not an executed solution. Leave at dusk with the crowds, or wait for curfew and thinner streets? Ask Naila about the camera group, or rely on a lit terminal ability? Copy the manifest — five world minutes, standing in a restricted site — or take the medicine and go? None of these has a correct answer. Each has a price the game states up front.',
      tableCaption: 'Design pillars and their hard edges',
      tableColumns: ['Pillar', 'What it means in play', 'What it forbids'],
      tableRows: [
        ['Surveillance is the antagonist', 'You are fighting a network, not guards', 'Omniscient detection'],
        ['Being seen is safe; being caught breaking rules is not', 'Public space stays usable', 'Paranoia-by-default'],
        ['Gates state exact paths before selection', 'You can predict every risk', 'Hidden dice or arithmetic'],
        ['Escape outranks confrontation', 'Break sight, hide, blend, talk', 'A combat loop'],
        ['The record is honest', 'Debrief states what happened', 'Invented praise or blame'],
      ],
      connectionsTitle: 'How the whole game fits together',
      connections: [
        'Dialogue and discovery produce facts. Facts open only their designated gates, George prompts, objectives, and map knowledge.',
        'One clock drives crowds, curfew, camera schedules, light, and the midnight deadline.',
        'The same geometry decides what you can see, what cameras can see, and where a sight line breaks.',
        'Paranoia is the visible condition of the protagonist; breakdown, capture, and midnight are the terminal outcomes.',
        'The debrief is written from recorded outcomes, so the ending can only claim what you actually did.',
      ],
      feedbackText: 'The city is the interface. The HUD holds four narrow lanes and nothing else; reading surfaces pause the world instead of racing it. Every warning names its source. If something feels unfair, that is a defect by definition — tension here comes from real stakes, never from withheld information.',
      recoveryTitle: 'Failure is a consequence, not a genre change',
      recoveryText: 'Three things end an attempt: breakdown when Paranoia reaches its internal ceiling, capture, or midnight arriving before the medicine is returned and transit is validated. Each failure states its exact cause. Restart Attempt restores the immutable operation-departure baseline — same cover, abilities, research, knowledge, and clock — and the night is yours to run differently.',
      recoveryPoints: [
        'Safehouse Rest costs thirty world minutes and reduces Paranoia by forty internal points without exposing that number in normal play.',
        'Restart Attempt restores the departure state exactly; nothing from the failed run leaks forward.',
        'Everything after departure — Paranoia events, discoveries, camera history, research, and outcomes — is discarded on restart.',
        'After completion, Continue Exploring keeps the district; End Demo closes the slice without pretending more exists.',
      ],
      seeAlsoTitle: 'Read next',
      seeAlsoLabels: ['Setting and Campaign', 'The Complete Level 0 Journey', 'Paranoia, Breakdown, and Recovery', 'Content Boundaries and Continuation'],
      closingTitle: 'The shortest definition',
      closingBody: 'Understand what the system can see, decide what you are willing to risk in front of it, and leave with the truth intact.',
    },
  }),
  chapter({
    id: 'setting',
    group: 'FOUNDATION',
    title: 'Setting and Campaign',
    summary: 'Hidzu Corporation runs Tokyo the way a utility runs power: identity, transit, logistics, and cameras in one civic promise. The frightening part is that it mostly works.',
    keywords: ['Tokyo 2036', 'Hidzu Corporation', 'Operation Cold Iron', 'Miami', 'expatriate'],
    sourceRefs: [source('20 Setting & Worldbuilding'), 'memory-bank/03 Lore/Plot Bible.md'],
    relatedChapterIds: ['identity', 'narrative', 'world', 'boundaries'],
    copy: {
      overviewTitle: 'A credible surveillance society',
      overviewText: 'In 2036 Hidzu Corporation is the infrastructure of ordinary life in Tokyo: your ID, your train, your deliveries, your safety. It is not a villain with searchlights. It is a service so useful that nobody argues with it, and so connected that one flagged inconsistency can follow a person everywhere the service reaches. The design rule for the whole setting: everything runs on a double reading. A kiosk is transit infrastructure and an identity checkpoint. A camera is a civic promise and a custody mechanism. The player learns to see the second meaning without the game ever claiming the first one is fake.',
      principleTitle: 'You start as nobody',
      principleBody: 'Hidzu Corporation does not consider you a problem when the night begins. There is no pre-existing flag, no warrant, no chase from scene one. Concern is earned — by breaking an observable rule in front of the network. This choice keeps public space genuinely usable and makes every escalation your own.',
      flowTitle: 'The local story inside the larger one',
      flowSteps: [
        'You left America after the Battle of Miami; your father has been missing since.',
        'His disappearance ties to Operation Cold Iron — a trans-Pacific surveillance and logistics program.',
        'You want passage to Miami to find out what happened. Passage requires people who move things quietly.',
        'Lira can arrange it — if you recover medical supplies Hidzu Corporation confiscated from her people.',
        'Inside the logistics site sits an optional shipping manifest linking Hidzu Corporation to Harrow and Cold Iron. Copying it is a choice, not a requirement.',
      ],
      exampleText: 'Harrow and ESD run the United States and are preparing Cold Iron; Hidzu Corporation supplies the identity and surveillance technology, and Eisenclave operates it on American soil. None of that is on screen tonight. Tonight is medicine, a district, and a train — but every institution above the district is real, and the manifest is where the two scales touch.',
      tableCaption: 'Campaign scaffolding',
      tableColumns: ['Element', 'Role tonight', 'Role in the campaign'],
      tableRows: [
        ['Tokyo', 'The whole playable world', 'Where you became worth watching'],
        ['Hidzu Corporation', 'The network you move through', 'Upstream supplier of control'],
        ['Cold Iron', 'A name on a manifest you may never see', 'The operation behind everything'],
        ['Eisenclave', 'Mentioned, absent', 'The American operator'],
        ['Miami', 'The destination on your ticket', 'The next game, not this one'],
      ],
      connectionsTitle: 'Setting expressed through systems',
      connections: [
        'The social feed shows what Hidzu Corporation wants believed: safety notices, curated sentiment, transit updates.',
        'Street schedules make the district feel inhabited and define what ordinary looks like at each hour.',
        'Surrealism stays metaphor — an absurd juxtaposition, never a supernatural fact.',
        'Japanese stays part of the fiction; what carries gameplay meaning is rendered readable.',
      ],
      feedbackText: 'Characters know only what they plausibly know. George labels fact, inference, and gap as three different things. The dossier records what you learned, not what the writers know. Nobody on the street delivers exposition about the conspiracy — the manifest, if you take it, speaks for itself.',
      recoveryTitle: 'Continuity survives a restart',
      recoveryText: 'Restart Attempt rewinds the night, not the world. Who you are, why you are here, what Lira asked, and what you learned before departure all hold. Only the operation itself — movement, evidence, discoveries, damage — resets. Failure never rewrites the setting and capture never becomes a playable prison.',
      recoveryPoints: [
        'The medicine is the mission whether or not you ever learn what Cold Iron is.',
        'Missing the manifest costs knowledge and a debrief line, nothing else.',
        'Capture and midnight each explain their own consequence in local, concrete terms.',
        'Completion records cover, abilities, research, facts, and outcomes in a form the next chapter can inherit.',
      ],
      seeAlsoTitle: 'Related chapters',
      seeAlsoLabels: ['What The Getaway Is', 'Narrative, Dialogue, George, and Contacts', 'World, District, Routes, and Mission Geometry', 'Content Boundaries and Continuation'],
      closingTitle: 'The setting test',
      closingBody: 'If an image could belong to any neon stealth game, it is wrong for this one. The city must feel like a service you would genuinely use — right up until it files you under evidence.',
    },
  }),
  chapter({
    id: 'journey',
    group: 'LEVEL 0',
    title: 'The Complete Level 0 Journey',
    summary: `One night, ${rules.level0DurationMinutes} real minutes, 18:30 to midnight on a ${rules.worldClockMultiplier} clock: choose a civilian cover, take the bargain, cross the district, bring back the medicine, validate your ticket, and read an honest account of what you did.`,
    keywords: ['walkthrough', 'medkits', 'Lira', 'dusk route', 'curfew route', 'departure', 'debrief'],
    sourceRefs: [source('11 Level 0 Vertical Slice Contract'), source('13 Level 0 Content and State Matrix')],
    relatedChapterIds: ['character', 'time', 'surveillance', 'narrative', 'knowledge'],
    copy: {
      overviewTitle: 'One complete operation',
      overviewText: `Level 0 is a complete story in ${rules.level0DurationMinutes} wall-clock minutes, outdoors, in one four-block district. It starts with you deciding who you are and ends with a debrief that only says what actually happened. In between sits one deliberately simple job — recover confiscated medkits, hand them to Lira, validate outbound transit before midnight — complicated by nothing except the city doing what the city does.`,
      principleTitle: 'Nothing important happens by proximity',
      principleBody: 'Walking near Lira does not accept her bargain. Standing at the cache does not take the medkits. Every transition that matters — accept, recover, return, validate, finish — is an explicit confirmed action. This is what keeps the record of your run true and the restart deterministic.',
      flowTitle: 'Chronological walkthrough',
      flowSteps: [
        `Choose among ${rules.covers} authored civilian covers. The Neighbor is playable now; the other three remain visible and disabled until their routes exist.`,
        `Wake up in the safehouse at ${rules.worldStart}. Your condition is Calm and the Neighbor's ${rules.startingAbilities} starting abilities are lit. George walks you into the night without a lecture.`,
        'Hear Lira out: what was taken, who needs it, what she can do about your ticket. Accept in so many words.',
        'Optionally see Naila (cameras, terminals, shipping data) or Brant (deliveries, service routines, how to look like you belong) — either order, one, both, or neither.',
        `Choose your window: leave into dusk crowds, or Wait in confirmed ${rules.safehouseStepMinutes}-minute steps toward the ${rules.curfew} curfew and its emptier service streets. Departure freezes the state a restart will return to.`,
        'Cross the district reading sight lines, schedules, and the mood of the street. Break rules only where nothing is watching, or be ready for what watching means.',
        `Open the cache, take the medkits. The manifest is right there: recognizing it takes Naila's warning or sharp eyes; copying it is a deliberate ${rules.manifestCopyMinutes}-world-minute act.`,
        'Get out, shake whatever concern you raised, and hand Lira the medkits — she has things to say about how you ran it.',
        `Validate at the outbound terminal before ${rules.deadline}, come home, debrief, rest if you need it, and review any ability learned through safehouse research.`,
        'Continue Exploring, or End Demo. Both are endings; neither pretends there is more city than there is.',
      ],
      exampleText: 'The fastest viable run skips both contacts, crosses during curfew, grabs the medkits, ignores the manifest, breaks one pursuit with a service recess, and validates with minutes to spare. It works, and the debrief will say exactly that: effective, underinformed, lucky once. A prepared dusk run reads as a different night entirely — same district, same rules, different person.',
      tableCaption: 'Phases and their gates',
      tableColumns: ['Phase', 'Hard requirement', 'Everything else'],
      tableRows: [
        ['Choose cover', 'Confirm the playable authored cover', 'The civilian history and abilities you carry'],
        ['Accept', 'Say yes to Lira', 'How the conversation goes'],
        ['Prepare', 'None', 'Contacts, waiting, reading the streets'],
        ['Operate', 'Medkits out of the site', 'Route, timing, terminal, manifest'],
        ['Return', 'Medkits in Lira’s hands', 'What she thinks of you'],
        ['Validate', `Terminal before ${rules.deadline}`, 'Rest, research, loose ends'],
        ['Conclude', 'Read the debrief', 'Continue Exploring or End Demo'],
      ],
      connectionsTitle: 'What each phase writes',
      connections: [
        'Cover selection writes identity and abilities. Conversations and discoveries write facts. Gates read only their declared paths.',
        'Departure writes the restart point — after preparation, before consequences.',
        'The operation writes evidence, Paranoia sources, camera history, and outcomes as they happen.',
        'Return and validation write completion; the debrief reads the ledger and adds nothing to it.',
      ],
      feedbackText: 'The current beat is always in the HUD, phrased as the next concrete thing. Objective changes announce themselves once, in world and in text. George can restate what is verified and explain what is blocking you; he cannot advance anything on your behalf.',
      recoveryTitle: 'Failure branches stay inside the night',
      recoveryText: 'Breakdown, capture, and midnight are endings with names and causes, not game-overs with a shrug. Each pauses the world, states exactly what happened, and offers Restart Attempt if an operation-departure baseline exists. Before departure there is nothing to restart — New Game is the honest option and the menu says so.',
      recoveryPoints: [
        'Midnight failure lists the unfinished requirements. It never implies you were caught.',
        'Capture shows a Hidzu Corporation incident report assembled only from what the network really saw.',
        'The manifest can be missed forever without blocking completion.',
        'Once medkits are returned and transit is validated, the deadline is satisfied — midnight cannot undo a finished job.',
      ],
      seeAlsoTitle: 'Detailed system chapters',
      seeAlsoLabels: ['Cover, Abilities, Gates, and Research', 'Time, Schedules, Safehouse, Save, and Restart', 'Surveillance, Cameras, Security, Civilians, and Needle', 'Narrative, Dialogue, George, and Contacts'],
      closingTitle: 'Journey shorthand',
      closingBody: 'Create → Accept → Prepare → Depart → Cross → Recover → Return → Validate → Debrief → Continue or End. Departure is the hinge: everything before it persists, everything after it is yours to lose.',
    },
  }),
  chapter({
    id: 'character',
    group: 'PLAYER',
    title: 'Cover, Abilities, Gates, and Research',
    summary: 'Choose an authored civilian life, carry binary abilities, and solve each deterministic gate through a lit ability, a designated fact, or a declared cost. Growth comes from safehouse research, never points or arithmetic.',
    keywords: ['cover', 'abilities', 'fragile', 'hardened', 'deterministic gates', 'facts', 'research'],
    sourceRefs: [source('92 Character, Covers, Abilities & Research'), source('13 Level 0 Content and State Matrix')],
    relatedChapterIds: ['condition', 'narrative', 'knowledge', 'journey'],
    copy: {
      overviewTitle: 'Identity is the life you lived',
      overviewText: `New Game presents ${rules.covers} authored covers of the same protagonist: Neighbor, Technician, Commuter, and Archivist. A cover fixes appearance, fiction, and ${rules.startingAbilities} starting abilities. Neighbor is the only playable cover in this slice; the other three remain visible and honestly disabled until their complete routes exist. There is no typed name, number allocation, equipment loadout, or hidden background bonus. The Character surface shows only the selected cover, current Paranoia condition, held abilities, research, verified facts, and long-term consequences.`,
      principleTitle: 'Binary identity, exact reasons',
      principleBody: 'An ability is held or absent. A held ability is lit or temporarily locked by Paranoia. A gate is met or not met through one explicitly selected path: ability, fact, or declared cost. The same inputs produce the same verdict before selection and after resolution. No dice, totals, modifiers, requirements, or invisible bonuses are involved.',
      flowTitle: 'From cover selection to research',
      flowSteps: [
        'Read all four cover fictions and their starting abilities. Disabled covers say that their authored route is not ready.',
        'Confirm Neighbor. The run starts with Read People, Negotiate, and Blend In and the matching grounded appearance.',
        'At a gate, inspect every path. Each option names the held or missing ability, known or unknown fact, locking Paranoia condition, or exact time/stress cost.',
        'Choose once. The result reuses the preview verdict and records the path and context; reopening cannot change it.',
        'Bring Naila’s camera-topology fact or Brant’s delivery-protocol fact to the safehouse. Research visibly consumes that fact and world time.',
        'Complete research once to gain Terminal Craft or Steady Voice. The new ability persists in the current attempt and cannot be researched twice.',
      ],
      exampleText: 'At the public entrance, Blend In is lit while Calm, so the social path is met. At Uneasy it is locked. Brant’s delivery-protocol fact can still meet the same gate, or the player can accept a ten-minute wait for a busier window. The route never becomes impossible, and the game never pretends the locked ability disappeared.',
      tableCaption: 'The Level 0 identity layers',
      tableColumns: ['Layer', 'Current rule', 'Hard boundary'],
      tableRows: [
        ['Cover', 'Authored fiction, appearance, and starting abilities', 'No free-text identity or point allocation'],
        ['Abilities', `${rules.abilities} binary authored capabilities`, 'No ranks, cooldowns, or generic bonuses'],
        ['Fragile / hardened', 'Fragile abilities lock at named Paranoia conditions; hardened abilities stay lit', 'No arithmetic penalty'],
        ['Facts', 'Knowledge with a stable identity and named source', 'No currency or universal buff'],
        ['Gates', 'Ability, fact, or declared cost with exact met/not-met reason', 'No random roll or hidden total'],
        ['Research', `${rules.researchOptions} one-use safehouse conversions`, 'No tree, grind, or allocation screen'],
      ],
      connectionsTitle: 'What reads identity',
      connections: [
        'Dialogue, terminals, blending, manifest recognition, and interception all use the same gate verdict model.',
        'A designated fact opens only its authored path; it never changes unrelated gates.',
        'Paranoia changes fragile-ability availability by named condition, while truth and known facts remain stable.',
        'George explains the current verdict from known state but cannot choose a path or reveal an unknown one.',
        'The debrief names the cover, abilities, facts, research, and accepted costs that actually mattered; it never grades the player.',
      ],
      feedbackText: 'Cover Select, Character, gate previews, gate results, and research use equivalent English and Ukrainian state. Lit, locked, held, missing, known, consumed, and unavailable are written labels rather than color-only hints. A blocked gate always names the exact missing key or locking condition.',
      recoveryTitle: 'Persistence and the anti-reroll rule',
      recoveryText: 'Finalized gate verdicts are immutable inside an attempt. Save validation checks the recorded gate, selected path, context, time, cover, abilities, facts, and Paranoia condition rather than trusting rendered copy. Restart Attempt restores the departure cover, held abilities, facts, research state, and pre-departure verdicts, then discards everything finalized later.',
      recoveryPoints: [
        'A disabled or unknown cover cannot initialize a run.',
        'An impossible cover, appearance, ability, fact, research, or verdict combination is refused on load rather than repaired.',
        'Research performed after departure is discarded by Restart Attempt; research performed before departure is part of the baseline.',
        'A finalized gate does not rerun because a panel closed, a save loaded, or Paranoia later changed.',
      ],
      seeAlsoTitle: 'Identity consequences elsewhere',
      seeAlsoLabels: ['Paranoia, Breakdown, and Recovery', 'Narrative, Dialogue, George, and Contacts', 'Facts, Dossier, Objectives, Minimap, Terminals, and Social Feed', 'The Complete Level 0 Journey'],
      closingTitle: 'The identity test',
      closingBody: 'The player should be able to say which life they chose, which abilities remain lit, which fact opens an alternative, and what a cost will change — without adding two numbers.',
    },
  }),
  chapter({
    id: 'condition',
    group: 'PLAYER',
    title: 'Paranoia, Breakdown, and Recovery',
    summary: 'Paranoia is honest surveillance stress presented only as Calm, Uneasy, Shaken, or Breaking. Rising conditions lock fragile abilities; a breakdown stages surrender and ends the attempt.',
    keywords: ['Paranoia', 'Calm', 'Uneasy', 'Shaken', 'Breaking', 'fragile abilities', 'breakdown', 'surrender'],
    sourceRefs: [source('43 Failure, Surrender & Recovery'), source('60 Paranoia')],
    relatedChapterIds: ['character', 'surveillance', 'stealth', 'time'],
    copy: {
      overviewTitle: 'One honest condition',
      overviewText: 'Paranoia is the protagonist’s physiological and cognitive strain under institutional observation. The runtime keeps precise internal state, but the player sees only named conditions: Calm, Uneasy, Shaken, and Breaking. It rises only from a communicated authored cause: observed rule-breaking, Suspicious verification, Pursuit, a dangerous escape, an interception consequence, or a story shock. Curfew, darkness, ordinary walking, and atmosphere alone never raise it.',
      principleTitle: 'Paranoia never lies',
      principleBody: 'Paranoia may lock a fragile ability and may end the attempt in breakdown, but it never invents an enemy, fakes a clue, distorts factual UI, rewrites a known fact, or applies an invisible modifier. The horror comes from losing access to practiced behavior while being watched, not from the game deceiving its player.',
      flowTitle: 'How condition moves',
      flowSteps: [
        'Start Calm. The HUD and Character surface show the condition name, never a player-facing score.',
        'When an authored source changes Paranoia, the feedback names the source and whether the condition intensified or eased.',
        'On first entry to Uneasy, Shaken, or Breaking, George gives one concise warning and the ability display updates immediately.',
        'Fragile abilities lock at their authored condition. Hardened abilities remain lit. Facts and factual UI do not change.',
        'Breaking observation stops surveillance-driven growth, but Paranoia does not passively decay while walking or waiting outdoors.',
        `A safehouse Rest costs ${rules.safehouseStepMinutes} world minutes and provides major recovery. One-use grounding actions and the first qualifying difficult escape provide smaller authored recovery.`,
        'If internal Paranoia reaches breakdown, the protagonist stages a surrender. The world pauses and the attempt ends as failure.breakdown.',
      ],
      exampleText: 'At Calm, Read People, Negotiate, and Blend In are lit. A sustained verification pushes the protagonist into Uneasy: all three become visibly locked, with Uneasy named as the reason. Brant’s fact and declared-cost paths still work. Rest later returns the protagonist to Calm and relights those abilities; no result, clue, or fact was falsified in between.',
      tableCaption: 'Player-facing Paranoia conditions',
      tableColumns: ['Condition', 'Ability effect', 'Player meaning'],
      tableRows: [
        ['Calm', 'All held abilities follow their normal state', 'Prepared behavior is available'],
        ['Uneasy', 'Fragile-at-Uneasy abilities lock', 'Social reading, negotiation, and blending become unreliable'],
        ['Shaken', 'Fragile-at-Shaken abilities also lock', 'Steady speech and pattern recognition become unreliable'],
        ['Breaking', 'All prior locks remain', 'One more severe escalation can end the attempt'],
        ['Breakdown', 'No gate can proceed', 'The protagonist surrenders; the attempt ends'],
      ],
      connectionsTitle: 'Sources and consumers',
      connections: [
        'Surveillance and authored consequences supply attributable events; Paranoia owns condition transitions and the immutable event ledger.',
        'Ability presentation reads the current condition; opening Character or previewing a gate changes nothing.',
        'Dialogue and gates use current lit/locked state but never read hidden arithmetic.',
        'Breakdown, capture, and midnight share one factual failure surface with cause-specific language.',
        'The debrief reports the peak condition, named sources, recoveries, and breakdown truth from the ledger.',
      ],
      feedbackText: 'The protagonist HUD lane always shows the condition name. Color supports but never replaces text. Each change names its source; each newly locked ability names the condition; each recovery says why it happened. Internal values are never printed to the player.',
      recoveryTitle: 'Breakdown and Restart Attempt',
      recoveryText: 'Breakdown ends the attempt immediately: simulation paused, surrender stated in plain words, source recorded. Capture and midnight use the same surface but never borrow breakdown language. Restart Attempt is offered only when a compatible departure baseline exists. Rest and grounding prevent failure; they cannot resurrect a terminal attempt.',
      recoveryPoints: [
        'Restart restores the departure Paranoia condition, ability states, and event history exactly.',
        'Post-departure grounding and escape recovery are discarded with the failed attempt.',
        'Breakdown is surrender under intolerable surveillance stress, never death, hallucination, or a combat transition.',
        'The save validator reconstructs every internal transition from the ordered event ledger; an impossible chain refuses to load.',
      ],
      seeAlsoTitle: 'Systems that feed condition',
      seeAlsoLabels: ['Cover, Abilities, Gates, and Research', 'Surveillance, Cameras, Security, Civilians, and Needle', 'Stealth, Hiding, Blending, Interception, and Escape', 'Time, Schedules, Safehouse, Save, and Restart'],
      closingTitle: 'The condition rule',
      closingBody: 'Every condition change has a source you were shown. Every lock names its condition. Every recovery costs something you chose. If the player needs a hidden number to understand what changed, the game broke its own law.',
    },
  }),
  chapter({
    id: 'movement',
    group: 'WORLD PLAY',
    title: 'Movement, Interaction, Camera, and Observation',
    summary: 'You steer, the game does not: direct WASD and click intent, collision sliding, explicit interactions, a close street-first camera, and a full-pause Observation mode for reading the city without spending it.',
    keywords: ['WASD', 'click-to-move', 'collision', 'interaction', 'Observation', 'camera', 'overview'],
    sourceRefs: [source('41 Movement, Interaction & Observation'), source('30 Art Direction (MVP)')],
    relatedChapterIds: ['world', 'surveillance', 'stealth', 'hud'],
    copy: {
      overviewTitle: 'Move yourself; read the city',
      overviewText: 'Movement is direct: WASD is continuous intent, a click is "go there" for a visible local spot, and new input overrides old input immediately. There is no route-finding. The game will slide you along a wall you walked into; it will not thread you around a corner you did not see. This is a deliberate refusal: the moment the game plans routes, it knows the district better than you do, and reading the district is the game.',
      principleTitle: 'Convenience never replaces agency',
      principleBody: 'A click states a destination, not a request for navigation. Unreachable means declined, with the reason. Interactions — pickups, contacts, terminals, entrances, hiding, blending, safehouse actions — fire only on explicit input from someone standing where the action lives. Nothing important triggers by walking past it.',
      flowTitle: 'Ordinary play',
      flowSteps: [
        'Hold a direction or click a spot; the protagonist moves at one honest speed and slides off obstacles.',
        'Read the street at eye level: entrances, camera housings, queue lines, shutters, cover.',
        'Stand at a thing, face it, press the action. If it refuses, the refusal names its reason — range, sight, schedule, state, or knowledge.',
        'Open Observation when you need to think: the whole simulation freezes — clock, cameras, Needle, crowds — while you pan and inspect what you already know.',
        'Zoom out deliberately for the composed four-block overview; come back down to play.',
      ],
      exampleText: 'Clicking beyond a building does not discover an alley for you. Either the destination is declined or you walk into the wall and slide — the wall was the information. Observation beside a sweeping camera freezes the sweep mid-arc; you can study its cone as long as you like, because studying is free and acting is not.',
      tableCaption: 'Control surfaces',
      tableColumns: ['Surface', 'Does', 'Does not'],
      tableRows: [
        ['WASD', 'Continuous direct movement', 'Auto-route'],
        ['Click', 'Local walkable destination', 'Pick a safe path'],
        ['Interact', 'One confirmed world action', 'Fire by proximity'],
        ['Observation', 'Full pause, pan, inspect known state', 'Reveal anything new'],
        ['Overview zoom', 'Orient across four blocks', 'Change the world'],
      ],
      connectionsTitle: 'One geometry, shared by everyone',
      connections: [
        'The same footprints resolve your collision, the cameras’ occlusion, and every entrance and anchor.',
        'What blocks your sight blocks theirs; there is no separate stealth geometry.',
        'Hiding and blending are authored places and behaviors, reachable by ordinary movement.',
        'The camera frames close play and overview from the same world — zoom never swaps the district.',
      ],
      feedbackText: 'A declined move or interaction says why, in one line, without suggesting an alternative route — suggestions are the pathfinder sneaking back in. Available actions show restrained prompts. Observation states plainly that the world is paused.',
      recoveryTitle: 'Input and state safety',
      recoveryText: 'Any owning overlay — dialogue, Character, this archive, failure — takes keyboard and pointer with it and returns them cleanly. No sacrificial click, no movement leaking under a dialog. Saves restore a validated walkable position; a corrupt position is refused rather than clamped into a wall.',
      recoveryPoints: [
        'Restart Attempt places you at the authored departure spot, facing the authored way.',
        'A refused interaction changes nothing — no fact, no device, no objective.',
        'Camera framing is rebuilt from world state on load; it is never saved as an opaque blob.',
        'Closing any overlay restores focus to the exact control that opened it.',
      ],
      seeAlsoTitle: 'Spatial systems',
      seeAlsoLabels: ['World, District, Routes, and Mission Geometry', 'Surveillance, Cameras, Security, Civilians, and Needle', 'Stealth, Hiding, Blending, Interception, and Escape', 'HUD and Information Architecture'],
      closingTitle: 'The movement test',
      closingBody: 'You should always be able to explain why you moved, stopped, slid, or were refused — by looking at the same street the game looked at.',
    },
  }),
  chapter({
    id: 'time',
    group: 'WORLD PLAY',
    title: 'Time, Schedules, Safehouse, Save, and Restart',
    summary: `The night runs ${rules.worldStart} to midnight at ${rules.worldClockMultiplier}. The street changes at exactly ${rules.windDownFirst}, ${rules.windDownSecond}, ${rules.curfew}, and ${rules.lastTransit} — and the clock is a resource you spend on purpose, never a queue you idle through.`,
    keywords: ['world clock', 'curfew', 'deadline', 'wind-down', 'safehouse', 'wait', 'rest', 'autosave', 'restart'],
    sourceRefs: [source('44 Safehouse, Save & Restart Attempt'), source('80 Day-Night Cycle')],
    relatedChapterIds: ['journey', 'surveillance', 'condition', 'narrative'],
    copy: {
      overviewTitle: 'Time is a route and a price',
      overviewText: `The world opens at ${rules.worldStart} and runs at ${rules.worldClockMultiplier} during active exploration — one real second is half a world minute. Four fixed boundaries restructure the street: ${rules.windDownFirst}, first announcements and early shutters; ${rules.windDownSecond}, the second wind-down as crowds thin and routes shift; ${rules.curfew}, curfew proper with its schedules and lighting; ${rules.lastTransit}, the last-train cadence that makes the remaining margin audible. Midnight is the deadline. Every reading and decision surface pauses all of it — reading the city never costs the city.`,
      principleTitle: 'Waiting is a decision, not a state',
      principleBody: `The safehouse advances time only in confirmed ${rules.safehouseStepMinutes}-minute steps — Wait for timing, Rest to reduce Paranoia by ${rules.restParanoiaReduction} internal points, or complete one declared research option for its exact time cost. There is no fast-forward lever on the street and no reward for standing in a corner while the clock spins. If curfew is your route, you choose it half an hour at a time, with the consequences printed.`,
      flowTitle: 'Planning, departure, and the baseline',
      flowSteps: [
        'Orient at the safehouse: brief, prepare, inspect your cover and abilities, research from a held fact, or step time forward deliberately.',
        'Each Wait or Rest previews its result — the new clock, the recovery, any boundary you will cross.',
        'Depart. The game writes the immutable Operation Attempt baseline first, then the autosave that says you left.',
        'Outside, one clock drives everything: schedules, camera behavior, light, crowd density, deadline.',
        'Return to the safehouse whenever you can reach it; the boundary is a door, not an amnesty — active concern and evidence follow you in conversation with the street.',
        'After the job is done, debrief and recovery run on paused time.',
      ],
      exampleText: `Talk to both contacts, come home, complete one research option, then Wait toward ${rules.curfew}: the district flips to service behavior — same geometry, different social truth. Fail at 23:58 with the ticket unvalidated and Restart Attempt restores your prepared departure, original clock and all. Not 18:30. Not a fresh cover. The exact night you assembled, ready to run again.`,
      tableCaption: 'Clock landmarks',
      tableColumns: ['Time', 'What changes', 'What it asks of you'],
      tableRows: [
        [rules.worldStart, 'Safehouse opens; dusk streets', 'Prepare, or go while crowds last'],
        [rules.windDownFirst, 'First announcements, early shutters', 'Note which cover is expiring'],
        [rules.windDownSecond, 'Second wind-down; routes and crowds shift', 'Choose your window'],
        [rules.curfew, 'Curfew schedules and lighting', 'Service behavior is the street now'],
        [rules.lastTransit, 'Last-transit cadence', 'The margin is now audible'],
        [rules.deadline, 'Deadline', 'Job done, or attempt over'],
      ],
      connectionsTitle: 'One clock, many consumers',
      connections: [
        'Schedules read the clock and swap civilian, security, and device phases at the four boundaries — each boundary fires exactly once, even across saves and pauses.',
        'Light and sound express the phase; they never run on a second clock of their own.',
        'Objectives and dialogue can read curfew and deadline state; nothing advances time by being on screen.',
        'Pauses compose: the world resumes only when every surface that paused it has released it.',
      ],
      feedbackText: 'Current time, curfew state, and the deadline live in the HUD permanently. Wait and Rest never surprise you — the result is printed on the button. Curfew announces itself in the world, in text, and in sound.',
      recoveryTitle: 'Autosave and Restart Attempt are different promises',
      recoveryText: 'Autosave is continuity: the current life of the run, resumable from the menu. Restart Attempt restores the Operation Attempt baseline: one immutable record of the moment you left, written transactionally before the autosave that records leaving. A crash can never produce a run that claims departure without holding the baseline to restart from. Before confirmation, George reads back its departure time, contacts consulted, Paranoia condition, cover, held abilities, and research — plus exactly what will be discarded.',
      recoveryPoints: [
        'Continue resumes the latest valid autosave and strips every transient overlay from it.',
        'Restart discards post-departure facts, movement, camera history, Paranoia events, research, and outcomes — all of it, every time.',
        'An incompatible older save states plainly that New Game is required; nothing half-migrates.',
        'A baseline that fails verification refuses to restore, with the reason, instead of guessing.',
      ],
      seeAlsoTitle: 'Time-sensitive systems',
      seeAlsoLabels: ['The Complete Level 0 Journey', 'Surveillance, Cameras, Security, Civilians, and Needle', 'Paranoia, Breakdown, and Recovery', 'Narrative, Dialogue, George, and Contacts'],
      closingTitle: 'The persistence rule',
      closingBody: 'Continue resumes a life; Restart Attempt replays a night. Neither invents a hybrid, and nothing the failed run learned comes back with you.',
    },
  }),
  chapter({
    id: 'surveillance',
    group: 'PRESSURE',
    title: 'Surveillance, Cameras, Security, Civilians, and Needle',
    summary: 'Being seen is safe. Being seen breaking a rule is the game: a fallible network that runs Clear → Suspicious → Pursuit on evidence, remembers last-known position instead of tracking you, and sends one unarmed drone named Needle to check its own doubts.',
    keywords: ['Clear', 'Suspicious', 'Pursuit', 'cameras', 'last-known position', 'Needle', 'civilians', 'camera loop'],
    sourceRefs: [source('42 Surveillance, Security & Civilian Behavior'), source('60 Paranoia')],
    relatedChapterIds: ['stealth', 'movement', 'condition', 'knowledge'],
    copy: {
      overviewTitle: 'The network knows evidence, not you',
      overviewText: 'Cameras, checkpoints, human security, one drone. Connected, and fallible on purpose. The network holds three states — Clear, Suspicious, Pursuit — and moves between them only on evidence. Its blind spots are honest ones: geometry, camera facing, range, and solid walls. No privacy zones, no off-grid tiles, no place that is safe by fiat — and no wall it can secretly see through either. What breaks its sight breaks its knowledge: once you leave view, it holds a last-known position and works from that, because it never had your live coordinates to begin with.',
      principleTitle: 'Visibility is not suspicion',
      principleBody: 'Walking past a camera does nothing. Concern requires the camera to watch you break a rule: entering a restricted area, touching a protected interaction, taking the medkits, failing verification, or a detected change to a camera feed. And when the network fully returns to Clear, recognition resets — you are one more commuter again until the next witnessed rule-break. Anonymity is the default, losable and recoverable.',
      flowTitle: 'Escalation and recovery',
      flowSteps: [
        'Clear: no concern, no last-known position. The street treats you as the street treats anyone.',
        'A camera watches you break a rule: concern is announced with its source, and a last-known position is set.',
        'Suspicious: the network verifies. Needle is dispatched to the evidence — the place it saw you, not the place you are.',
        'Keep feeding it sightings and it hardens to Pursuit: confirmed identity evidence, active search.',
        'Break sight, move away from where it last knew you, use a credible context — recovery runs Pursuit → Suspicious → Clear, in stages, never in one jump.',
        'Back at Clear, recognition is gone. The camera that caught you an hour ago does not know you now.',
      ],
      exampleText: 'You cross the restricted logistics lane; the lane camera sees it. Suspicious, source announced, last-known set at the lane. You round a solid corner — its cone dies at the wall, and so does its information. Needle hums toward the lane while you are two blocks away in a service recess. The search plays out around old evidence, finds nothing, and steps down. The system worked exactly as designed and still lost you: that distance between its confidence and its knowledge is the whole game.',
      tableCaption: 'Network states',
      tableColumns: ['State', 'The network holds', 'Your opening'],
      tableRows: [
        ['Clear', 'Nothing that concerns you', 'Move openly; pick your moment'],
        ['Suspicious', 'A source and a last-known position', 'Break sight; be elsewhere credibly'],
        ['Pursuit', 'Confirmed identity evidence', 'Stage down through Suspicious — no shortcuts'],
      ],
      connectionsTitle: 'The cast of the network',
      connections: [
        'Camera cones are drawn from the same geometry that detects — the rendered cone is the true cone. Nearby active cameras also leak tells: device light, IR glint, reflections.',
        'Civilians are scenery with eyes, not sensors: they glance at what is visibly odd and step around trouble, but they never read network state and never report you.',
        'Security verifies, blocks, and intercepts on schedule; guards carry no weapons and no health bars because there is nothing to fight.',
        'Needle — the one verifier drone — flies a fixed ritual patrol, hums so you hear it coming, warns before approaching, warns before verifying, cannot be fought, and cannot arrest. It confirms; humans act.',
        'The district has exactly one connected camera group, loopable once per attempt at its terminal. Its history — untouched, active, clean, or traced — outlives the loop itself, until Restart Attempt wipes the slate.',
      ],
      feedbackText: 'Restraint is Clear, amber is concern, crimson is confirmed danger — each paired with words and sound, never color alone. Sweep, focus, dispatch, verification, state change, trace, and step-down all have distinct cues. Observation shows exact cones for devices you have discovered; the rest of the network you infer the way anyone infers a camera: by looking.',
      recoveryTitle: 'Evidence must stay breakable',
      recoveryText: 'Suspicious is always recoverable until a distinct event confirms identity. Waiting in open view clears nothing — the network does not get bored. A hiding or blending context can refuse you for stated reasons: watched right now, out of range, wrong schedule, full, or missing prerequisite. What it can never do is grant invisibility while a camera is looking at you entering it.',
      recoveryPoints: [
        'Save and load carry the full network truth: concern, sources, last-known, camera-feed history, searches, and Needle’s errand.',
        'Restart Attempt restores a Clear network with no memory of the failed run.',
        'Walking into the safehouse never launders an active pursuit.',
        'Capture states which evidence confirmed you, on the same failure surface as everything else.',
      ],
      seeAlsoTitle: 'Pressure and escape',
      seeAlsoLabels: ['Stealth, Hiding, Blending, Interception, and Escape', 'Movement, Interaction, Camera, and Observation', 'Paranoia, Breakdown, and Recovery', 'Facts, Dossier, Objectives, Minimap, Terminals, and Social Feed'],
      closingTitle: 'The fairness test',
      closingBody: 'At any moment you can answer four questions: what is watching, what does it last know, what changed its mind, and what would credibly break the evidence. If any answer is missing, the network is cheating.',
    },
  }),
  chapter({
    id: 'stealth',
    group: 'PRESSURE',
    title: 'Stealth, Hiding, Blending, Interception, and Escape',
    summary: 'No stealth button, no magic darkness: escape is built from broken sight lines, changed direction, authored places to hide, authored crowds to join, and — if it comes to hands — a short deterministic interception resolved through declared abilities, facts, or costs.',
    keywords: ['hiding', 'blending', 'line of sight', 'interception', 'escape', 'service recess', 'delivery queue'],
    sourceRefs: [source('70 Stealth'), source('50 Combat')],
    relatedChapterIds: ['surveillance', 'movement', 'character', 'condition'],
    copy: {
      overviewTitle: 'Stealth is a sequence, not a mode',
      overviewText: 'There is no crouch-and-vanish. What exists: the network’s current sight, its last-known information, your actual movement, and a set of authored contexts — places that hide you, behaviors that absorb you — each with rules you can learn. Darkness is not one of them: a shadow with no authored context is just a shadow. This is the cost of honesty; if darkness worked everywhere, the district’s carefully built sight lines would mean nothing.',
      principleTitle: 'A context is a place or behavior with rules',
      principleBody: 'A service recess hides you — after sight is broken, if it is not watched, if it is in service hours. A delivery queue blends you — while the routine is actually running, if you plausibly belong. Every context states its schedule, capacity, and prerequisites, and every refusal names the rule you missed. Entry under direct observation is always refused: cameras do not forget what they are currently looking at.',
      flowTitle: 'From exposed to gone',
      flowSteps: [
        'Before the risky move, know your exits: which wall breaks which cone, which context is live at this hour.',
        'When concern lands, break the sight line first — a solid corner ends the network’s live information.',
        'Then move against expectation: away from your last-known position, not around it.',
        'Enter a valid context and let the search exhaust itself around old evidence.',
        'Step down Pursuit → Suspicious → Clear; leave only when the next move is credible.',
        'If security reaches you anyway, interception is short and deterministic: each option names its required lit ability, designated fact, or explicit cost. Noise, when it matters, is an authored event — a knocked shutter, a dropped crate — never a simulated footstep meter.',
      ],
      exampleText: 'At dusk, Brant’s routine makes the delivery queue readable and you blend through the watched crossing. During curfew the queue does not exist — but the service recess behind the workshop does, once the corner kills the camera’s line. Same district, opposite tools. If a sweep guard corners you, a lit Steady Voice ability can produce a documented warning; Slip Away offers another authored path. A final failed option is capture — a report, not a fight scene.',
      tableCaption: 'Escape tools and their limits',
      tableColumns: ['Tool', 'Works when', 'Never'],
      tableRows: [
        ['Hiding', 'Sight broken, authored place, valid hour', 'Any dark tile'],
        ['Blending', 'The routine is live and you fit it', 'Generic crowd immunity'],
        ['Camera loop', 'The one connected group, at its terminal, once', 'District blackout'],
        ['Interception', 'A lit ability, designated fact, or declared cost supports the option', 'A combat round'],
        ['Recovery', 'Evidence broken and stages walked', 'Pursuit to Clear in one hop'],
      ],
      connectionsTitle: 'Escape spends the whole sheet',
      connections: [
        'Movement and geometry produce the actual sight break — no ability substitutes for a wall.',
        'Surveillance supplies what is watching and what it last knew; stealth is played against that record.',
        'The clock decides which contexts exist right now; dusk and curfew are different toolkits.',
        'Facts from Naila and Brant turn specific contexts and terminals from gambles into plans.',
        'Paranoia, time, facts, and route consequences are the declared prices an ugly escape can demand.',
      ],
      feedbackText: 'Live contexts read as occupied or available without the game outlining every safe spot from across the street. Refusals are specific. The search visibly orbits the evidence, so you can watch the network being wrong. Interception pauses the world, prints requirements and costs, and resumes real time on the outcome.',
      recoveryTitle: 'No shortcut around consequence',
      recoveryText: 'A successful interception can still cost Paranoia, time, a fact, or a route consequence when the option said it would. A failed final option is capture, with the confirming evidence named. Saves preserve occupied contexts and active searches exactly; the only clean slate is Restart Attempt, which rebuilds the departure baseline.',
      recoveryPoints: [
        'Standing in the open never clears a network that still holds evidence.',
        'No context leaks your live position to pursuers — hidden is hidden.',
        'Recovery stages cannot be skipped by any action, item, ability, or fact.',
        'Nothing in the slice initializes a fight: no weapon, no enemy health, no combat grid.',
      ],
      seeAlsoTitle: 'Supporting chapters',
      seeAlsoLabels: ['Surveillance, Cameras, Security, Civilians, and Needle', 'Movement, Interaction, Camera, and Observation', 'Cover, Abilities, Gates, and Research', 'Paranoia, Breakdown, and Recovery'],
      closingTitle: 'The stealth test',
      closingBody: 'Every successful escape should be retellable as a story about geometry, timing, and nerve — never as "the mode worked".',
    },
  }),
  chapter({
    id: 'narrative',
    group: 'STORY',
    title: 'Narrative, Dialogue, George, and Contacts',
    summary: 'Four voices, no meters: Lira sets the stakes, Naila and Brant sell knowledge that changes plans, and George — your private AI — organizes what is verified without ever playing the game for you.',
    keywords: ['Lira', 'Naila', 'Brant', 'George', 'dialogue', 'gates in conversation', 'debrief'],
    sourceRefs: [source('35 Narrative Alignment'), source('40 George (AI Companion)'), source('90 Dialogue')],
    relatedChapterIds: ['setting', 'character', 'knowledge', 'journey'],
    copy: {
      overviewTitle: 'People are systems without becoming meters',
      overviewText: 'Nobody in this game has a trust bar. Lira offers a concrete bargain — medicine for passage — and reacts to what you actually do about it. Naila knows cameras, terminals, and shipping data. Brant knows deliveries, service routines, and how belonging looks from the inside. George is a private AI riding along: a fourth HUD lane and a small AR presence who sorts what you know into verified fact, reasonable inference, and open gap. Relationships here are made of facts and outcomes, because a number that goes up when you say nice things is a slot machine wearing a face.',
      principleTitle: 'Exact words, exact consequences',
      principleBody: 'Every option shows the exact line you will say. Every gated option states each valid path before selection, then records the path that resolved it. A failed nonterminal choice always leads somewhere worse-but-real — a harder route, a declared cost, a changed reception — never to a wall that demands a reload. Only the final capture-escape gate can end the attempt itself.',
      flowTitle: 'Conversation through the night',
      flowSteps: [
        'George opens the night with context and controls — a colleague, not a narrator.',
        'Lira lays out the medkits, the midnight condition, and the passage. You accept in words, or not yet.',
        'Naila and Brant are optional, in any order. Each sells a different lens on the same district; neither hands out permission slips.',
        'George speaks when something verified changes — a fact, an objective, the network’s state, a blocker. When he has nothing, he says nothing, and silence never hides information: if something useful is unavailable, he tells you why.',
        'Returning to Lira, the conversation is built from your route, your facts, your condition, and what actually happened on the way.',
        'The debrief closes the loop: done, learned, missed, and what rides with you toward Miami.',
      ],
      exampleText: 'Naila: "the annex cameras hang off one terminal — loop the group and the lane goes blind, but sloppy work leaves fingerprints." That sentence is a fact with teeth: the terminal option gains its stated context, the risk is named, and a lit Terminal Craft ability or its declared alternative decides the rest. Brant’s version of power is a schedule: when the queue forms, who stands in it, what a uniform is worth at 21:30. Neither conversation is required. Both change what the district is.',
      tableCaption: 'The cast and their edges',
      tableColumns: ['Voice', 'Gives', 'Will not'],
      tableRows: [
        ['Lira', 'Stakes, bargain, judgment of results', 'Post a quest and vanish'],
        ['Naila', 'Camera topology, terminals, shipping data', 'Do the technical work for you'],
        ['Brant', 'Delivery timing, service behavior, blending', 'Hand over a route key'],
        ['George', 'Verified summaries, blockers, reasons for silence', 'Invent, decide, or act in the world'],
        ['You', 'The exact printed line you chose', 'Get paid for clicking every node'],
      ],
      connectionsTitle: 'Dialogue shares state with everything',
      connections: [
        'Facts born in conversation are the same facts the dossier, declared gates, minimap, and debrief consume.',
        'Options read your lit abilities, designated facts, condition, and the clock; locked options print every valid missing path.',
        'George reads verified state only; he has no hands — he cannot move, hack, or change the world.',
        'History stays reviewable, and both languages carry identical meaning through stable choice identities.',
      ],
      feedbackText: 'Dialogue pauses the world. The speaking portrait, exact printed options, and shared gate verdict are the entire interface — no hidden approval ticks, arithmetic, or timers pressuring the read. Closing a conversation never auto-confirms the highlighted line.',
      recoveryTitle: 'Fail-forward, and what restart keeps',
      recoveryText: 'Unmet or costed social paths write consequences, not save-scumming prompts: a worse price, a cooler welcome, a longer way around. Finalized choices persist through save and load. Restart Attempt keeps every conversation from before departure and erases the night’s aftermath — Lira remembers your preparation, not your failure.',
      recoveryPoints: [
        'Missing dialogue content refuses loudly instead of improvising a line.',
        'No conversation can be farmed by reopening it; finalized gate verdicts stay finalized.',
        'George states insufficient evidence as such — he does not fill gaps with confidence.',
        'The debrief can name what you never found without punishing you for the style of your run.',
      ],
      seeAlsoTitle: 'Narrative truth elsewhere',
      seeAlsoLabels: ['Setting and Campaign', 'Cover, Abilities, Gates, and Research', 'Facts, Dossier, Objectives, Minimap, Terminals, and Social Feed', 'The Complete Level 0 Journey'],
      closingTitle: 'The dialogue test',
      closingBody: 'A conversation succeeded if it changed what you understand or what you can credibly attempt. Visiting every node is not a virtue and the game will never pay you for it.',
    },
  }),
  chapter({
    id: 'knowledge',
    group: 'STORY',
    title: 'Facts, Dossier, Objectives, Minimap, Terminals, and Social Feed',
    summary: 'Knowledge is state with provenance: binary facts with named sources, a dossier that says how you know, a minimap that only shows what you found, three one-function terminals, and one manifest with its own explicit chain.',
    keywords: ['facts', 'dossier', 'objectives', 'minimap', 'terminals', 'manifest', 'social feed'],
    sourceRefs: [source('46 Facts, Dossier, Minimap & Terminals'), source('47 Social Feed'), source('91 Quests & Objectives')],
    relatedChapterIds: ['narrative', 'surveillance', 'hud', 'journey'],
    copy: {
      overviewTitle: 'Knowledge is persistent state',
      overviewText: 'A fact is binary — you know it or you do not — with a stable identity, a named source, and designated consumers. Facts reveal, clarify, unlock, or satisfy only the gates specifically wired to them; there is no general "cluefulness" score quietly improving every situation. One thing in the district earns a richer model: the Cold Iron manifest runs an explicit chain — unknown, warned by Naila, recognized in the cache, copied. Copying is its own decision: five world minutes standing in a hostile site, no arithmetic required, just the question of whether the truth is worth the exposure.',
      principleTitle: 'The interface knows only what you know',
      principleBody: 'The minimap opens with the safehouse, Lira, and whatever you can physically see. Objectives phrase the next beat as concretely as your knowledge allows and no more. Cameras you have not discovered do not render as cones anywhere — not on the map, not in Observation. There is no fog-of-war being theatrically peeled; there is simply nothing drawn where you have learned nothing.',
      flowTitle: 'From discovery to consequence',
      flowSteps: [
        'Learn something — from a person, a terminal, a document, or your own eyes. The fact records its source.',
        'Read it back in the dossier, phrased as what you know and how you know it, inference labeled as inference.',
        'Watch its designated consumers change: one gate path satisfied, one option clarified, one map annotation added.',
        'Use terminals for their single functions: one loops the connected camera group, one operates the cache, one validates outbound transit. No terminal does two jobs.',
        'Skim the social feed for the city’s official mood — propaganda, notices, curated sentiment, transit alerts. It reads; it never posts.',
        'Every objective and outcome event is written explicitly, so the debrief reports completion from the record, not from inference.',
      ],
      exampleText: 'Naila tells you which cameras hang off the terminal: the dossier gains the relationship, the terminal option gains its context, the minimap marks the connected cameras you now understand — and nothing else changes, because that fact was wired to exactly those three consumers. The feed, meanwhile, is cheerfully reporting record transit reliability while you read it from inside a restricted lane.',
      tableCaption: 'Information surfaces and their authority',
      tableColumns: ['Surface', 'Owns', 'Refuses'],
      tableRows: [
        ['Fact ledger', 'What is known, from where, since when', 'Display-only pseudo-facts'],
        ['Dossier', 'Readable knowledge with provenance', 'Omniscient lore'],
        ['Objectives', 'The current beat, at known precision', 'A quest wall'],
        ['Minimap', 'Discovered places and devices', 'Routing and hidden intel'],
        ['Terminals', 'One function each, three total', 'Universal hacking'],
        ['Social feed', 'The institutional mood, read-only', 'A social simulation'],
      ],
      connectionsTitle: 'Where knowledge flows',
      connections: [
        'Conversations and physical discovery produce facts; a designated fact can satisfy an authored recognition gate.',
        'George, objectives, dossier, minimap, and terminals consume facts under their own visibility rules.',
        'Surveillance discovery decides which devices the map and Observation may show as known.',
        'The outcome ledger records what happened for the debrief; it is bookkeeping, not player knowledge.',
      ],
      feedbackText: 'A new fact lands with one concise announcement and a dossier entry — no fanfare, no feed of collectibles. Terminal use pauses the world, states its single function and requirement, and reports its result, including whether the work left a trace.',
      recoveryTitle: 'No accidental knowledge across attempts',
      recoveryText: 'Autosave keeps legitimately acquired knowledge. Restart Attempt keeps only what you knew at departure: the manifest chain, post-departure discoveries, camera-feed history, and outcome events all reset. New Game starts from authored knowledge, not from what the previous player remembers — the game cannot stop you from knowing the district, but it will never pretend the protagonist does.',
      recoveryPoints: [
        'An undiscovered target changes no fact, no objective, no map.',
        'A missed manifest leaves no phantom dossier entry — absence is recorded as absence.',
        'A traced camera loop records both the local result and the fingerprint it left.',
        'The debrief never infers a route or a discovery from display logs; if it was not recorded, it did not happen.',
      ],
      seeAlsoTitle: 'Knowledge consumers',
      seeAlsoLabels: ['Narrative, Dialogue, George, and Contacts', 'Surveillance, Cameras, Security, Civilians, and Needle', 'HUD and Information Architecture', 'The Complete Level 0 Journey'],
      closingTitle: 'The knowledge test',
      closingBody: 'For anything the game shows as known, it can answer: who learned it, from what source, and which specific decisions it is allowed to touch. One system — the manifest — earns states beyond yes and no, and it earns them by being the story.',
    },
  }),
  chapter({
    id: 'hud',
    group: 'PRESENTATION',
    title: 'HUD and Information Architecture',
    summary: `Four narrow lanes in ${rules.hudHeight} of the screen — minimap, protagonist, George, current beat — and everything deeper runs as a pausing overlay, including this archive. The city keeps the pixels.`,
    keywords: ['four lanes', 'dock', 'overlays', 'pause', 'F1', 'search', 'focus', 'archive'],
    sourceRefs: [source('45 HUD & Information Architecture'), source('Game Design')],
    relatedChapterIds: ['knowledge', 'condition', 'narrative', 'equivalence'],
    copy: {
      overviewTitle: 'Persistent truth, optional depth',
      overviewText: `The permanent interface is one dock, ${rules.hudHeight} of the viewport, four lanes: knowledge minimap, protagonist (cover, named Paranoia condition, and ability state), George, and the current beat. That is the entire standing footprint. Everything richer — Character, dossier, dialogue, terminals, debrief, failure, and this Game Design Bible — is an overlay that takes focus, pauses the simulation, and gives both back on close. The design position: a surveillance game about reading a city cannot bury the city under instrumentation.`,
      principleTitle: 'The district is the interface',
      principleBody: 'No duplicate objective panels, no scrolling event log, no permanent world labels, no minimap routing, no chat window. If information is not needed to act in the next thirty seconds, it belongs in an overlay you chose to open.',
      flowTitle: 'Using this archive',
      flowSteps: [
        'Open it from the start menu, the paused menu, or F1 during eligible play.',
        'F1 yields to owning surfaces: creation, dialogue, terminals, debrief, failure, and text inputs keep their keys.',
        'While open, the world is fully paused — clock, cameras, Needle, crowds, everything.',
        'Search covers titles, summaries, section names, body text, and keywords in both languages.',
        'Navigate by chapter rail, in-chapter contents, or the narrow-screen drawer; your place is kept for the session.',
        'Close with Escape or the close control; focus returns exactly where it was borrowed from.',
      ],
      exampleText: 'Opening this page mid-crossing is safe by construction: the sweep freezes mid-arc, the clock holds, and Paranoia accrues nothing while you read. Pressing F1 again does nothing — closing a reading surface is a deliberate act, not a key bounce. Escape first closes the drawer if it is open, then clears an active search, then closes the archive.',
      tableCaption: 'Archive layout by viewport',
      tableColumns: ['Width', 'Navigation', 'Reading surface'],
      tableRows: [
        ['1200px and up', 'Chapter rail with inline contents', 'Centered column, 76-character measure'],
        ['841–1199px', 'Condensed rail', 'Same column, tighter margins'],
        ['840px and below', 'Full-screen drawer, 44px targets', 'Single column, tables scroll locally'],
      ],
      connectionsTitle: 'One overlay contract',
      connections: [
        'Every overlay owns a composable pause reason; the world resumes only when all owners release.',
        'Reading state — chapter, section, query, drawer — is session-local and never enters the save.',
        'The same overlay rules govern dialogue, terminals, and failure: focus taken, world paused, focus returned.',
        'Both languages present identical structure, rules, and numbers with naturally different prose.',
      ],
      feedbackText: 'Amber marks your active thread through the archive; the reading surface stays monochrome and calm. Current chapter and section are always visible, search reports its result count, and every control is reachable by keyboard in a contained focus loop.',
      recoveryTitle: 'Focus, pause, and teardown safety',
      recoveryText: 'Opening is idempotent and closing is symmetric: each surface releases exactly the pause it acquired, no matter how it closes — control, Escape, unmount, or a New Game underneath it. If the menu already paused the world, the archive rides along and closing it leaves the menu’s pause intact.',
      recoveryPoints: [
        'Opening from the start menu creates no run and touches no state.',
        'Saves and restarts strip transient overlay state entirely.',
        'A remembered section that no longer exists falls back to the first valid one.',
        'If the control that opened the archive is gone, focus lands on the shell’s safe default.',
      ],
      seeAlsoTitle: 'Information and equivalence',
      seeAlsoLabels: ['Facts, Dossier, Objectives, Minimap, Terminals, and Social Feed', 'Paranoia, Breakdown, and Recovery', 'Narrative, Dialogue, George, and Contacts', 'Audio, Localization, Accessibility, and Performance'],
      closingTitle: 'The interface test',
      closingBody: 'You can always read deeply without paying time for it, and you can always get back to the exact control you left. An interface that costs mission time to understand has failed at its one job.',
    },
  }),
  chapter({
    id: 'world',
    group: 'PRODUCTION',
    title: 'World, District, Routes, and Mission Geometry',
    summary: `Exactly ${rules.districtBlocks} continuous blocks, ${rules.districtIdentities} functional identities, and ${rules.districtLoops} named loops — Transit Road, Market Ring, Outer Space — small enough to author every sight line, dense enough to read as Tokyo.`,
    keywords: ['four blocks', 'Transit Road', 'Market Ring', 'Outer Space', 'routes', 'entrances', 'anchors'],
    sourceRefs: [source('30 Art Direction (MVP)'), source('41 Movement, Interaction & Observation')],
    relatedChapterIds: ['movement', 'surveillance', 'art', 'journey'],
    copy: {
      overviewTitle: 'A place first, a level second',
      overviewText: `The district is exactly ${rules.districtBlocks} dense, continuous city blocks — not nine, not a compound, not a backdrop with a playable strip. Three functional identities share them: public and civic life, logistics and control, service and escape. Three loops tie them together, and the loops have names the city actually uses: Transit Road, the public spine; Market Ring, the commercial and logistics circuit; Outer Space, the perimeter where the district lets go. Signage says these names, civilians say them, and George says them — wayfinding is part of the fiction, not a HUD layer.`,
      principleTitle: 'Every object earns its place',
      principleBody: 'Buildings exist to make street walls, sight lines, entrances, and recognizable corners. Props exist where they serve navigation, hiding, blending, or the feeling of a street that people use. Anything that is only decoration competes with the things that matter, so it does not ship.',
      flowTitle: 'Reading the district',
      flowSteps: [
        'Orient from the safehouse by landmark and loop name, at street level, before ever opening the map.',
        'Walk to Lira and the optional contacts on ordinary connected sidewalks — nothing teleports.',
        'Plan against identity: public streets have crowds and cameras; logistics has rules and evidence; service has shadows and shutters.',
        'Find every mission element in visible geometry: entrances, cameras, the cache, hiding spots, the outbound terminal.',
        'Zoom to the composed overview when you need the whole shape; the district does not simplify into tokens.',
      ],
      exampleText: 'Suspicious on Market Ring, you have real choices because the loops interlock: cut toward Transit Road and its crowds, or peel to Outer Space and its long dark edges. A player who knows the three names can improvise a route under pressure. That is the test the geometry was built to pass.',
      tableCaption: 'The three identities',
      tableColumns: ['Identity', 'Reads as', 'Plays as'],
      tableRows: [
        ['Public / civic', 'Ordinary evening city', 'Contacts, crowds, blending, visible watchers'],
        ['Logistics / control', 'Hidzu Corporation infrastructure', 'The cache, terminals, cameras, restricted lanes'],
        ['Service / escape', 'Back-of-house Tokyo', 'Recesses, sight breaks, the curfew route'],
      ],
      connectionsTitle: 'One geometry, one truth',
      connections: [
        'The mission skeleton owns required places and route purposes under stable identities.',
        'The authored city owns the visible footprints and streets those purposes live in.',
        'A single reconciled record supplies walkability, collision, occlusion, entrances, and anchors to every system.',
        'What the player sees, what blocks movement, and what blocks camera sight are the same shapes.',
      ],
      feedbackText: 'Orientation comes from silhouettes, corners, signage, light, and the three loop names before it comes from any marker. The minimap confirms what the street already taught; it never substitutes for it.',
      recoveryTitle: 'Spatial integrity across saves',
      recoveryText: 'Saved positions must sit inside the accepted walkable district under the same world version, or the load is refused with the reason. Restart Attempt rebuilds the district to its departure state — devices, schedules, and all — and places you at the authored departure point.',
      recoveryPoints: [
        'Collision, visible footprints, entrances, and anchors stay mutually aligned by construction.',
        'The overview changes framing only; no zoom level swaps or simplifies the world.',
        'World detail never obscures a required lane, interaction, warning, or person.',
        'A mismatched world record fails loudly rather than loading you inside a wall.',
      ],
      seeAlsoTitle: 'World consumers',
      seeAlsoLabels: ['Movement, Interaction, Camera, and Observation', 'Surveillance, Cameras, Security, Civilians, and Needle', 'Art, Production, Actors, Portraits, and Lighting', 'The Complete Level 0 Journey'],
      closingTitle: 'The world test',
      closingBody: 'First it reads as a believable place; then you notice every street, corner, and camera was authored for one night’s work. Both readings must survive the whole game.',
    },
  }),
  chapter({
    id: 'art',
    group: 'PRODUCTION',
    title: 'Art, Production, Actors, Portraits, and Lighting',
    summary: 'Graphic surveillance noir: one coherent Neo Tokyo architectural identity, a close 2:1 street frame with the protagonist low-center, separate grounded actors, matching portraits, and practical light that follows the schedule.',
    keywords: ['surveillance noir', 'Neo Tokyo', 'isometric', 'actors', 'portraits', 'lighting'],
    sourceRefs: [source('30 Art Direction (MVP)'), source('48 Actors & Portraits'), 'memory-bank/04 Engineering/3D-to-2D Sprite Pipeline (Blender POC).md'],
    relatedChapterIds: ['world', 'equivalence', 'hud', 'setting'],
    copy: {
      overviewTitle: 'Graphic surveillance noir',
      overviewText: 'The palette is a decision about who owns light. Readable midtones and ink silhouettes carry the city; sodium amber belongs to practical fixtures; cyan belongs to Hidzu Corporation devices and nothing else; crimson appears only where danger or restriction is real. No broad neon washes, no fantasy skyline — institutional dystopia is served by the city looking normal. The architecture is one coherent identity: a licensed Neo Tokyo kit recomposed into a single four-block master scene, every building placed with provenance, so the district holds together like a place instead of a collage.',
      principleTitle: 'The camera serves play',
      principleBody: 'Normal play is a close, street-first 2:1 isometric frame with the protagonist in the lower-center lead — near enough to read faces, doors, and device lights. Maximum zoom-out lands on one deliberately composed four-block overview. Nothing between exists as a default: framing is a designed range, not a slider left to chance.',
      flowTitle: 'From authored city to live frame',
      flowSteps: [
        'Compose the full four-block relationship in one master scene, mission semantics intact.',
        'Prove the frame at street level and at overview from the same geometry.',
        'Reconcile visible footprints with collision, occlusion, entrances, and anchors before anything ships.',
        'Place actors as separate grounded figures: 64×96, eight facings, idle, move, and interact — about fifteen percent larger than strict architectural scale, because readable people outrank perfect perspective.',
        'Carry each face from creation through HUD to dialogue portrait as one continuous identity.',
        'Light by schedule: dusk, wind-down, curfew — practical sources first, and actors pick up a subtle amber or cyan cast from the lit regions they stand in. The tint is presentation only; it never touches detection or play.',
      ],
      exampleText: 'At street scale: a concrete wall in cold midtone, a sodium lamp marking the service door, one cyan pinpoint that means a camera is alive. At overview: the same blocks, loops, and thresholds, still legible, with people still people rather than icons. If a frame could be mistaken for a generic neon game, the frame is wrong — the reference is a working city at night, photographed by someone who knows what to fear in it.',
      tableCaption: 'Presentation contracts',
      tableColumns: ['Layer', 'Required', 'Prohibited'],
      tableRows: [
        ['Architecture', 'One specific coherent identity', 'A collage of unrelated facades'],
        ['Camera', 'Close play plus one composed overview', 'Board-game default framing'],
        ['Actors', 'Separate grounded figures, shared anchors', 'People baked into backgrounds'],
        ['Portraits', 'One face from creation to dialogue', 'Generic stand-in faces'],
        ['Lighting', 'Practical, schedule-aware, readable', 'Broad glow or crushed black'],
      ],
      connectionsTitle: 'Art serves system truth',
      connections: [
        'The geometry the art shows is the geometry the game plays: collision, occlusion, entrances, anchors.',
        'Camera cones and device lights display the same surveillance truth detection uses.',
        'Actor scale and separation keep the social read — who is where, facing what — alive at all supported zooms.',
        'The HUD borrows the same restraint so the interface never outdresses the world.',
      ],
      feedbackText: 'Color never acts alone: every danger, focus, or restriction pairs its hue with shape, text, or sound. The protagonist stays in the lower-center lead during normal play, and the things that matter — doors, devices, people — survive every supported viewport.',
      recoveryTitle: 'Visual correctness is gameplay correctness',
      recoveryText: 'If the drawn world and the simulated world disagree, the player is being lied to with pixels — that is a defect of the same severity as a false rule. A missing asset resolves to a neutral diagnostic figure, never to a silently substituted character. Zoom cannot swap architecture. Saves store meaning, not screenshots of state.',
      recoveryPoints: [
        'Building bases, doors, occluders, and devices stay registered at every zoom.',
        'The actor light tint eases in and out and can never alter detection, schedule, or interaction.',
        'A failed asset is visible as a failure — diagnostics over illusion.',
        'Presentation state is rebuilt from world truth on every load.',
      ],
      seeAlsoTitle: 'Presentation context',
      seeAlsoLabels: ['World, District, Routes, and Mission Geometry', 'Audio, Localization, Accessibility, and Performance', 'HUD and Information Architecture', 'Setting and Campaign'],
      closingTitle: 'The art test',
      closingBody: 'One still frame should say: a modern watched city, an ordinary person in it, a route decision waiting, and pressure without a single word of UI. If the frame needs a label, the frame is not done.',
    },
  }),
  chapter({
    id: 'equivalence',
    group: 'PRESENTATION',
    title: 'Audio, Localization, Accessibility, and Performance',
    summary: 'Two languages, many bodies, one game: every critical meaning survives translation, color-blindness, silence, reduced motion, and small screens — and the three ambience sources keep the street walls alive.',
    keywords: ['audio', 'Ukrainian', 'English', 'accessibility', 'captions', 'reduced motion', 'performance'],
    sourceRefs: [source('49 Audio'), source('45 HUD & Information Architecture'), source('30 Art Direction (MVP)')],
    relatedChapterIds: ['hud', 'art', 'knowledge', 'surveillance'],
    copy: {
      overviewTitle: 'Equivalent meaning, not equal pixels',
      overviewText: 'English and Ukrainian are peers: same content identities, same rules, same numbers, same structure, naturally different sentences. Japanese stays in the world as fiction and is rendered readable where it carries gameplay meaning. Accessibility follows the same standard as localization — the target is equivalent decisions, not decorated sameness. A player who cannot hear the cue or see the color must still receive the cause, the state, and the way out.',
      principleTitle: 'No critical meaning lives in one channel',
      principleBody: 'Color pairs with shape and label. Sound pairs with readable state. Motion has a reduced alternative that preserves timing and meaning. Keyboard access reaches every choice a pointer can. If any single channel fails and the player loses a decision, the design was wrong, not the player.',
      flowTitle: 'The sonic and semantic street',
      flowSteps: [
        'The city sounds inhabited by authorship, not by accident: three threshold ambience sources — a restaurant on Transit Road, a workshop on Market Ring, an apartment by the safehouse — leak life through their walls.',
        'Needle’s hum, approach warning, and verification warning are a learnable vocabulary of exactly three sounds.',
        'Network transitions, curfew, objectives, safehouse actions, failures, and completion each own a distinct cue family.',
        'Nothing speaks: the slice ships without voice acting, and text carries every line.',
        'Captions and text equivalents cover surveillance and consequence audio.',
        'Text scales, focus stays visible, and no supported viewport hides a control or a warning.',
      ],
      exampleText: 'Suspicious arrives as amber presentation, a state line with its source, and its audio signature — three channels, one meaning. Mute the game and the state line remains. The Ukrainian line reads naturally rather than word-for-word, while naming the same cause, state, and available response as the English.',
      tableCaption: 'Equivalence contracts',
      tableColumns: ['Risk', 'Primary channel', 'Guaranteed alternative'],
      tableRows: [
        ['Camera attention', 'Device light and motion', 'Discovered cones and a named source'],
        ['Network state', 'Palette and audio', 'State label with source and recovery'],
        ['Gate outcome', 'Option styling', 'Met or unmet path with exact reason'],
        ['Condition change', 'Gauge motion and cue', 'Source and new named tier in text'],
        ['Deadline pressure', 'Last-transit cadence', 'Clock and requirement warning in the HUD'],
      ],
      connectionsTitle: 'Shared semantic events',
      connections: [
        'One domain event fans out to text, world presentation, and audio; presentation never owns state.',
        'This archive is the same book in both languages: identical structure and rules, page for page.',
        'Audio priorities, cooldowns, and ducking keep repeated events from shouting over new ones.',
        'Performance protects the accepted composition — the world does not shrink to buy frames.',
      ],
      feedbackText: 'One-shot cues cannot be replayed by interface churn. Search and section changes announce politely to assistive tech. Tables carry captions and headers. Focus loops are contained. Long Ukrainian strings get room instead of truncation.',
      recoveryTitle: 'Graceful degradation',
      recoveryText: 'A missing optional asset degrades to silence plus the readable alternative — never to a lost decision. Missing required localized content is a validation failure before it is ever a player experience. Performance pressure may cut cosmetic cost, but never a gameplay object, a warning, or a person.',
      recoveryPoints: [
        'Audio ownership is cleaned up on every scene and overlay change — no orphaned loops.',
        'Focus falls back to a safe control when its origin disappears.',
        'Reduced motion preserves every timing that carries meaning.',
        'Saves store semantic state only — never display strings, never playback positions.',
      ],
      seeAlsoTitle: 'Presentation systems',
      seeAlsoLabels: ['HUD and Information Architecture', 'Art, Production, Actors, Portraits, and Lighting', 'Facts, Dossier, Objectives, Minimap, Terminals, and Social Feed', 'Surveillance, Cameras, Security, Civilians, and Needle'],
      closingTitle: 'The equivalence test',
      closingBody: 'Two players — different language, different senses, different hardware — face the same information, the same risks, and the same choices. Anything less is a difficulty setting nobody asked for.',
    },
  }),
  chapter({
    id: 'boundaries',
    group: 'SCOPE',
    title: 'Content Boundaries and Continuation',
    summary: 'The slice is small on purpose: no combat loop, no inventory economy, no procedural story — one authored night, finished properly, with a handoff the campaign can trust.',
    keywords: ['scope', 'no combat', 'no inventory', 'Continue Exploring', 'End Demo', 'Miami handoff'],
    sourceRefs: [source('50 Combat'), source('93 Inventory (MVP)'), source('10 MVP Spine')],
    relatedChapterIds: ['identity', 'journey', 'setting', 'character'],
    copy: {
      overviewTitle: 'A narrow slice with whole-game identity',
      overviewText: 'Level 0 is one night that contains the entire idea of the game: a civilian cover you chose, a bargain you accepted, a district that watches, and an exit you have to earn. The inventory of content is short and deliberate — one mission, two optional contacts, two timings, four blocks, three terminals, one manifest, one drone, one debrief, and two bounded research options. Depth per element beats breadth in every trade, because a small thing finished is a promise kept and a large thing sketched is a promise broken.',
      principleTitle: 'What is out stays out',
      principleBody: 'No combat loop, weapons, or enemy health. No inventory grid, equipment, economy, or crafting. No procedural dialogue or generated story. No reputation meters, no vehicles, no survival needs, no mandatory errands. These are exclusions with reasons, not gaps waiting for content: each one would move the game’s center of gravity away from watching, knowing, and leaving.',
      flowTitle: 'How the edges hold',
      flowSteps: [
        'Mission objects are explicit state: the medkits, the ticket, the manifest. No backpack abstraction between you and them.',
        'Danger resolves through movement, timing, contexts, and words — and at worst, one short deterministic interception.',
        'Confrontation failing means capture and a report, in the same grammar as every other ending.',
        'Completion needs two explicit acts: medkits to Lira, validation at the terminal, both before midnight.',
        'Then: Continue Exploring in the finished district, or End Demo. No fake door to a next level.',
        'What persists — cover, abilities, research, facts, and outcomes — is shaped for the campaign to inherit honestly.',
      ],
      exampleText: 'Taking the medkits updates the cache and the objective — no icon lands in a grid. The manifest becomes knowledge, not loot. A failed interception writes an incident report, not a respawn. Where other games would open a subsystem, this one closes a loop instead.',
      tableCaption: 'Scope register',
      tableColumns: ['Area', 'In the slice', 'Not in the slice'],
      tableRows: [
        ['Confrontation', 'Short authored interception choices', 'A combat system'],
        ['Objects', 'Explicit mission state', 'Inventory management'],
        ['Story', 'Authored dialogue, facts, outcomes', 'Procedural generation'],
        ['Social', 'A read-only institutional feed', 'Posting and followers'],
        ['World', 'Four outdoor blocks, fully authored', 'Interiors and extra districts'],
        ['Campaign', 'A compatible handoff record', 'A playable Miami'],
      ],
      connectionsTitle: 'Why the walls make the game better',
      connections: [
        'No combat keeps surveillance, composure, and escape as the only grammar of danger.',
        'Explicit objects keep objectives, facts, and the debrief perfectly synchronized.',
        'Authored content keeps every gate, fact, and outcome testable and true.',
        'Four blocks buy the density that makes one district worth learning by heart.',
      ],
      feedbackText: 'The interface never advertises absent systems — no dimmed weapon slots, no locked crafting tab. What the game does not do, it does not show. Completion offers its two endings in plain words, and the debrief distinguishes done, skipped, and never-found without inventing a grade.',
      recoveryTitle: 'Honest endings, compatible futures',
      recoveryText: 'A failed run restarts from departure with its cause on record. A completed run keeps its district, its identity, and its ledger. End Demo closes the promise the slice made; it does not tease one it cannot keep. The campaign will consume this record when it exists — and until it exists, nothing pretends otherwise.',
      recoveryPoints: [
        'Saves from older shapes of the game are refused plainly rather than migrated into nonsense.',
        'Restart Attempt never carries post-departure objects or outcomes backward.',
        'Continue Exploring cannot re-arm the deadline or duplicate completed research.',
        'Future systems must extend the record without rewriting what tonight meant.',
      ],
      seeAlsoTitle: 'Return to the whole design',
      seeAlsoLabels: ['What The Getaway Is', 'The Complete Level 0 Journey', 'Setting and Campaign', 'Cover, Abilities, Gates, and Research'],
      closingTitle: 'The scope test',
      closingBody: 'Every included system pushes watching, knowing, or leaving. Every excluded system would have pushed something else. That is the whole argument, and the slice is the proof.',
    },
  }),
];
