export const GAME_BIBLE_SHARED_RULES = {
  level0DurationMinutes: '15–20',
  worldStart: '18:30',
  worldClockMultiplier: '30×',
  windDownFirst: '21:00',
  windDownSecond: '21:30',
  curfew: '22:00',
  lastTransit: '23:30',
  deadline: '00:00',
  districtBlocks: 4,
  districtIdentities: 3,
  districtLoops: 3,
  paranoiaMinimum: 0,
  paranoiaMaximum: 100,
  paranoiaTiers: [
    { id: 'calm', internalRange: '0–39' },
    { id: 'uneasy', internalRange: '40–69' },
    { id: 'shaken', internalRange: '70–89' },
    { id: 'breaking', internalRange: '90–99' },
  ],
  paranoiaAnnouncements: '40, 70, 90',
  groundingMinutes: 10,
  groundingRelief: 10,
  escapeRelief: 5,
  covers: 4,
  playableCovers: 1,
  abilities: 9,
  startingAbilities: 3,
  researchOptions: 2,
  appearances: 4,
  verifierDrones: 1,
  manifestCopyMinutes: 5,
  persistentHudLanes: 4,
  hudHeight: '16–18%',
  safehouseStepMinutes: 30,
  restParanoiaReduction: 40,
} as const;
