export const GAME_BIBLE_SHARED_RULES = {
  level0DurationMinutes: '15–20',
  worldStart: '18:30',
  worldClockMultiplier: '30×',
  windDownFirst: '21:00',
  windDownSecond: '21:30',
  curfew: '22:00',
  lastTransit: '23:30',
  deadline: '00:00',
  districtBlocks: 4,
  districtIdentities: 3,
  districtLoops: 3,
  healthMinimum: 0,
  healthMaximum: 100,
  paranoiaMinimum: 0,
  paranoiaMaximum: 100,
  paranoiaPenalties: [
    { range: '0–39', modifier: '0' },
    { range: '40–69', modifier: '−1' },
    { range: '70–89', modifier: '−2' },
    { range: '90–99', modifier: '−3' },
    { range: '100', modifier: 'fatal' },
  ],
  paranoiaAnnouncements: '40, 70, 90',
  groundingMinutes: 10,
  groundingRelief: 10,
  escapeRelief: 5,
  creationAttributePoints: 4,
  creationSkillPoints: 6,
  attributes: 4,
  skills: 8,
  attributeStart: 1,
  attributeCreationCap: 3,
  skillCreationCap: 2,
  longTermCap: 5,
  levelSkillPoints: 2,
  attributeEveryLevels: 3,
  appearances: 4,
  verifierDrones: 1,
  manifestCopyMinutes: 5,
  persistentHudLanes: 4,
  hudHeight: '16–18%',
  safehouseStepMinutes: 30,
  restHealth: 100,
  restParanoiaReduction: 40,
} as const;
