// Generated by scripts/generate-grounded-character-assets.ts. Do not edit by hand.

export interface GeneratedAssetIntegrity {
  sha256: string;
  compressedBytes: number;
  decodedBytes: number;
}

export const GENERATED_ACTOR_PROVENANCE = {
  "recipeId": "get206-grounded-actor-v3",
  "recipe": {
    "path": "art/actors/get206/manifests/grounded-actor-recipe.json",
    "sha256": "06143b06297a8c024121898f121a4cee415ee487d41f3cc542881e46b0bad44c"
  },
  "generator": {
    "path": "the-getaway/scripts/generate-grounded-character-assets.ts",
    "sha256": "d35aa83b116291361886bc932fd5a145e1cfc7245aa9444caa88724b3ca06968"
  },
  "pngLibrary": {
    "path": "the-getaway/scripts/lib/rgbaPng.ts",
    "sha256": "b5a9da812d1aad82d27849f0c2b64d4ba9293457955a712bc09827889e49ec2e"
  },
  "spriteReference": {
    "id": "get206-grounded-cast-board-v1",
    "path": "art/actors/get206/references/grounded-cast-board-v1.png",
    "sha256": "bc16333c07710bd9bf3d78f1dc32e082bc6585cdce280c3a7fbf6bb107f433aa"
  },
  "portraitReference": {
    "id": "get206-grounded-portrait-board-v1",
    "path": "art/actors/get206/references/grounded-portrait-board-v1.png",
    "sha256": "72545015a1d9cb3a78143a666a5bb941ed0bc69385247972988e23c4f4469d54"
  }
} as const;

export const ACTOR_PORTRAIT_INTEGRITY: Record<string, GeneratedAssetIntegrity> = {
  "player_civilian_01": {
    "sha256": "3d915c1d82118b8cea97eee8aa39c603659138258d1810034d73c2054abb5d6e",
    "compressedBytes": 123748,
    "decodedBytes": 262144
  },
  "player_civilian_02": {
    "sha256": "6a9d72e5a0c1f007a01d389fcbe1327fe8e5e75f11f244bfcac6fa27b644d26e",
    "compressedBytes": 127007,
    "decodedBytes": 262144
  },
  "player_civilian_03": {
    "sha256": "7eed98895d03599c0b12431cd98945300f7b7f01b517f66636799b270e0c487c",
    "compressedBytes": 124479,
    "decodedBytes": 262144
  },
  "player_civilian_04": {
    "sha256": "8629991bf30e9792c72377d1f03ed6ee753360f58593c62c283b2d59bc04ac1b",
    "compressedBytes": 130021,
    "decodedBytes": 262144
  },
  "contact_lira": {
    "sha256": "5762cffd8937897ae8eca411910289ecdcba93a90f8e38b01fd10f746eec59b2",
    "compressedBytes": 130444,
    "decodedBytes": 262144
  },
  "contact_naila": {
    "sha256": "d5e474771a969070409a4856617233eabb552a75cdc63ba920ee85db50fffb25",
    "compressedBytes": 126717,
    "decodedBytes": 262144
  },
  "contact_brant": {
    "sha256": "2a239e6ee1604b99fd3d0c12cc415589edbfeedcaafd860f4d434d45fd5077e6",
    "compressedBytes": 133334,
    "decodedBytes": 262144
  },
  "security_hidzu_identity": {
    "sha256": "27fd634ffe34174c769fe6e86f41d02f080a690e8810f083800739ae4b8492e0",
    "compressedBytes": 122920,
    "decodedBytes": 262144
  },
  "security_hidzu_service": {
    "sha256": "1f789da26afcb6f3760c24838b3866aada4c82b07f581a71a12fba37fa68ac5c",
    "compressedBytes": 124589,
    "decodedBytes": 262144
  },
  "civilian_transit": {
    "sha256": "3757081f8c721988650836ef0dc1dc22ef1793f17cdcc3f5d52b287d39b3089b",
    "compressedBytes": 128098,
    "decodedBytes": 262144
  },
  "civilian_service": {
    "sha256": "27fd735c4e73cd0d02885971a8ed13714688588ed874e9d52610ccc0491966cc",
    "compressedBytes": 122381,
    "decodedBytes": 262144
  },
  "civilian_delivery": {
    "sha256": "c9637bba5982239f9e93918073540298034bb4135d8d5a62abcc7999b7a94b93",
    "compressedBytes": 123187,
    "decodedBytes": 262144
  }
};

export const NON_WORLD_PRESENTATION_INTEGRITY: Record<string, GeneratedAssetIntegrity> = {
  "takahiroBroadcast": {
    "sha256": "07bfd26e87fc24fc02dad65d8720c3f856a2b0e6c826e987cf21ce454e2b90d9",
    "compressedBytes": 127300,
    "decodedBytes": 262144
  },
  "georgeAr": {
    "sha256": "7693b8e7d97e9cd518032facd0a90469ed04ca8863e93d0e9898ad519c9401bc",
    "compressedBytes": 63595,
    "decodedBytes": 262144
  }
};
