// Generated by scripts/generate-grounded-character-assets.ts. Do not edit by hand.

export interface GeneratedAssetIntegrity {
  sha256: string;
  compressedBytes: number;
  decodedBytes: number;
}

export const GENERATED_ACTOR_PROVENANCE = {
  "recipeId": "get206-grounded-actor-v2",
  "recipe": {
    "path": "art/actors/get206/manifests/grounded-actor-recipe.json",
    "sha256": "2ee82d62ce2c4957cd8b09c10b882d2c5f8fc7fa596a4124095f2f91bc447c9f"
  },
  "generator": {
    "path": "the-getaway/scripts/generate-grounded-character-assets.ts",
    "sha256": "14444161b8e2a83aecbce1ced77943e108f435d185660334835acbdc7453e007"
  },
  "pngLibrary": {
    "path": "the-getaway/scripts/lib/rgbaPng.ts",
    "sha256": "caca24465ec948f5bda07f1ebdeb05635211c549a21bd0d5ccd9e4bc02409f9d"
  },
  "spriteReference": {
    "id": "get206-grounded-cast-board-v1",
    "path": "art/actors/get206/references/grounded-cast-board-v1.png",
    "sha256": "bc16333c07710bd9bf3d78f1dc32e082bc6585cdce280c3a7fbf6bb107f433aa"
  },
  "portraitReference": {
    "id": "get206-grounded-portrait-board-v1",
    "path": "art/actors/get206/references/grounded-portrait-board-v1.png",
    "sha256": "72545015a1d9cb3a78143a666a5bb941ed0bc69385247972988e23c4f4469d54"
  }
} as const;

export const ACTOR_PORTRAIT_INTEGRITY: Record<string, GeneratedAssetIntegrity> = {
  "player_civilian_01": {
    "sha256": "3d915c1d82118b8cea97eee8aa39c603659138258d1810034d73c2054abb5d6e",
    "compressedBytes": 123748,
    "decodedBytes": 262144
  },
  "player_civilian_02": {
    "sha256": "6a9d72e5a0c1f007a01d389fcbe1327fe8e5e75f11f244bfcac6fa27b644d26e",
    "compressedBytes": 127007,
    "decodedBytes": 262144
  },
  "player_civilian_03": {
    "sha256": "7eed98895d03599c0b12431cd98945300f7b7f01b517f66636799b270e0c487c",
    "compressedBytes": 124479,
    "decodedBytes": 262144
  },
  "player_civilian_04": {
    "sha256": "8629991bf30e9792c72377d1f03ed6ee753360f58593c62c283b2d59bc04ac1b",
    "compressedBytes": 130021,
    "decodedBytes": 262144
  },
  "contact_lira": {
    "sha256": "5762cffd8937897ae8eca411910289ecdcba93a90f8e38b01fd10f746eec59b2",
    "compressedBytes": 130444,
    "decodedBytes": 262144
  },
  "contact_naila": {
    "sha256": "d5e474771a969070409a4856617233eabb552a75cdc63ba920ee85db50fffb25",
    "compressedBytes": 126717,
    "decodedBytes": 262144
  },
  "contact_brant": {
    "sha256": "2a239e6ee1604b99fd3d0c12cc415589edbfeedcaafd860f4d434d45fd5077e6",
    "compressedBytes": 133334,
    "decodedBytes": 262144
  },
  "security_hidzu_identity": {
    "sha256": "27fd634ffe34174c769fe6e86f41d02f080a690e8810f083800739ae4b8492e0",
    "compressedBytes": 122920,
    "decodedBytes": 262144
  },
  "security_hidzu_service": {
    "sha256": "1f789da26afcb6f3760c24838b3866aada4c82b07f581a71a12fba37fa68ac5c",
    "compressedBytes": 124589,
    "decodedBytes": 262144
  },
  "civilian_transit": {
    "sha256": "3757081f8c721988650836ef0dc1dc22ef1793f17cdcc3f5d52b287d39b3089b",
    "compressedBytes": 128098,
    "decodedBytes": 262144
  },
  "civilian_service": {
    "sha256": "27fd735c4e73cd0d02885971a8ed13714688588ed874e9d52610ccc0491966cc",
    "compressedBytes": 122381,
    "decodedBytes": 262144
  },
  "civilian_delivery": {
    "sha256": "c9637bba5982239f9e93918073540298034bb4135d8d5a62abcc7999b7a94b93",
    "compressedBytes": 123187,
    "decodedBytes": 262144
  }
};

export const NON_WORLD_PRESENTATION_INTEGRITY: Record<string, GeneratedAssetIntegrity> = {
  "takahiroBroadcast": {
    "sha256": "b0090ceb4fc8bec8f77f2a2794114988cca1ad727cdb879890842a0a0a84001a",
    "compressedBytes": 8264,
    "decodedBytes": 262144
  },
  "georgeAr": {
    "sha256": "8d476e8c621431d58b620cb4577a41758c825c201d7a29f098e8a83d6cc8ad56",
    "compressedBytes": 3821,
    "decodedBytes": 262144
  }
};
