import type {
  Level0Anchor,
  Level0BuildingFootprint,
  Level0LayoutContract,
  Level0SurfaceRegion,
  WorldPolygon,
} from '../../../game/level0/layout/types';

const rect = (left: number, top: number, right: number, bottom: number): WorldPolygon => [
  { x: left, y: top },
  { x: right, y: top },
  { x: right, y: bottom },
  { x: left, y: bottom },
];

const surface = (
  id: string,
  kind: Level0SurfaceRegion['kind'],
  left: number,
  top: number,
  right: number,
  bottom: number
): Level0SurfaceRegion => ({
  id,
  kind,
  polygon: rect(left, top, right, bottom),
  walkable: kind !== 'blocked' && kind !== 'interior-boundary',
});

const building = (
  id: string,
  functionName: string,
  left: number,
  top: number,
  right: number,
  bottom: number,
  height: number
): Level0BuildingFootprint => ({
  id,
  function: functionName,
  polygon: rect(left, top, right, bottom),
  height,
});

const anchor = (
  id: string,
  kind: Level0Anchor['kind'],
  x: number,
  y: number,
  radius: number,
  ownerId?: string,
  tags?: string[]
): Level0Anchor => ({
  id,
  kind,
  position: { x, y },
  radius,
  required: true,
  ownerId,
  tags,
});

const buildingFootprints = [
  building('building.public_market', 'public-market', 9.5, 9.5, 22.5, 25.5, 5),
  building('building.civic_north', 'civic-services', 27.5, 9.5, 39.5, 27, 7),
  building('building.hidzu_offices', 'hidzu-offices', 44.5, 9.5, 56.5, 27, 8),
  building('building.logistics_annex', 'logistics-compliance', 61.5, 9.5, 74.5, 22, 6),
  building('building.safehouse', 'safehouse-shell', 9.5, 33, 22.5, 45, 4),
  building('building.service_west', 'service-workshops', 27.5, 33, 39.5, 50.5, 5),
  building('building.transit_hall', 'transit-hall', 44.5, 33, 56.5, 41.5, 5),
  building('building.service_south', 'service-distribution', 61.5, 33, 74.5, 50.5, 5),
  building('building.transit_services', 'transit-services', 48, 41.5, 57, 51, 7),
];

export const LEVEL0_LAYOUT_CONTRACT: Level0LayoutContract = {
  id: 'level0-tokyo-greybox-v3',
  schemaVersion: 2,
  projection: {
    tileWidth: 64,
    tileHeight: 32,
    orientation: 'isometric-2:1',
  },
  bounds: rect(0, 0, 84, 60),
  zones: [
    { id: 'zone.safehouse', name: 'Safehouse edge', polygon: rect(4, 33, 39, 56) },
    { id: 'zone.public', name: 'Public market', polygon: rect(4, 4, 39, 33) },
    { id: 'zone.transit', name: 'Transit spine', polygon: rect(22, 4, 62, 56) },
    { id: 'zone.logistics', name: 'Hidzu logistics', polygon: rect(45, 4, 80, 40) },
  ],
  traversalLoops: [
    {
      id: 'loop.outer',
      name: 'District perimeter',
      closed: true,
      points: [
        { x: 7, y: 7 },
        { x: 25, y: 7 },
        { x: 42, y: 7 },
        { x: 59, y: 7 },
        { x: 77, y: 7 },
        { x: 77, y: 53 },
        { x: 59, y: 53 },
        { x: 42, y: 53 },
        { x: 25, y: 53 },
        { x: 7, y: 53 },
        { x: 7, y: 30 },
        { x: 7, y: 7 },
      ],
    },
    {
      id: 'loop.public',
      name: 'Public preparation loop',
      closed: true,
      points: [
        { x: 25, y: 7 },
        { x: 42, y: 7 },
        { x: 42, y: 30 },
        { x: 25, y: 30 },
        { x: 25, y: 7 },
      ],
    },
    {
      id: 'loop.service',
      name: 'Service and return loop',
      closed: true,
      points: [
        { x: 42, y: 30 },
        { x: 59, y: 30 },
        { x: 59, y: 53 },
        { x: 42, y: 53 },
        { x: 42, y: 30 },
      ],
    },
  ],
  surfaces: [
    surface('surface.road.outer_north', 'road', 4, 5, 80, 9),
    surface('surface.road.outer_south', 'road', 4, 51, 80, 55),
    surface('surface.road.outer_west', 'road', 5, 5, 9, 55),
    surface('surface.road.outer_east', 'road', 75, 5, 79, 55),
    surface('surface.road.central', 'road', 4, 28, 80, 32),
    surface('surface.avenue.west', 'road', 23, 5, 27, 55),
    surface('surface.avenue.central', 'road', 40, 5, 44, 55),
    surface('surface.avenue.east', 'road', 57, 5, 61, 55),
    surface('surface.safehouse.court', 'plaza', 10, 45, 19, 51),
    surface('surface.public.forecourt', 'plaza', 9, 25.5, 23, 28),
    surface('surface.logistics.apron', 'plaza', 60, 17, 62, 22),
    surface('surface.logistics.service_alley', 'alley', 61, 22, 75, 28),
    surface('surface.transit.plaza', 'plaza', 44.5, 41.5, 48, 51),
    surface('surface.sidewalk.market', 'sidewalk', 9, 25, 23, 28),
    surface('surface.sidewalk.civic', 'sidewalk', 27, 26.5, 40, 28),
    surface('surface.sidewalk.hidzu', 'sidewalk', 44, 26.5, 57, 28),
    surface('surface.sidewalk.logistics', 'sidewalk', 61, 27.5, 75, 28),
    surface('surface.crossing.west', 'crossing', 23, 28, 27, 32),
    surface('surface.crossing.central', 'crossing', 40, 28, 44, 32),
    surface('surface.crossing.east', 'crossing', 57, 28, 61, 32),
  ],
  buildingFootprints,
  entrances: [
    {
      id: 'entrance.logistics.public',
      buildingId: 'building.logistics_annex',
      position: { x: 61, y: 20 },
      facingDegrees: 225,
      route: 'public',
    },
    {
      id: 'entrance.logistics.service',
      buildingId: 'building.logistics_annex',
      position: { x: 68, y: 22.5 },
      facingDegrees: 315,
      route: 'service',
    },
    {
      id: 'entrance.safehouse',
      buildingId: 'building.safehouse',
      position: { x: 16, y: 45.5 },
      facingDegrees: 135,
      route: 'shared',
    },
  ],
  droneRegions: [
    {
      id: 'drone.region.logistics-verification',
      polygon: rect(56, 14, 79, 31),
      launchAnchorId: 'drone.launch',
    },
  ],
  anchors: [
    anchor('safehouse.boundary', 'safehouse', 16, 48.25, 3.5, 'building.safehouse'),
    anchor('safehouse.spawn', 'safehouse', 16, 47, 0.8, 'building.safehouse'),
    anchor('safehouse.departure', 'safehouse', 18, 50, 1.2, 'building.safehouse'),
    anchor('entrance.safehouse', 'entrance', 16, 45.5, 1.2, 'building.safehouse', ['shared']),
    anchor('contact.lira', 'contact', 16, 27, 1.4, 'contact.lira'),
    anchor('contact.naila', 'contact', 25, 17, 1.4, 'contact.naila'),
    anchor('contact.brant', 'contact', 42, 17, 1.4, 'contact.brant'),
    anchor('entrance.logistics.public', 'entrance', 61, 20, 1.2, 'building.logistics_annex', ['public']),
    anchor('entrance.logistics.service', 'entrance', 68, 22.5, 1.2, 'building.logistics_annex', ['service']),
    anchor('terminal.camera_loop', 'terminal', 59, 20, 1.2, 'camera.group.logistics'),
    anchor('terminal.cache_locker', 'terminal', 68, 25, 1.2, 'objective.medkits'),
    anchor('terminal.outbound_transit', 'terminal', 14, 45.5, 1.2, 'building.safehouse'),
    anchor('drone.launch', 'drone-launch', 73, 27, 1.4, 'drone.verifier.01'),
    anchor('hide.service_recess', 'hiding', 63, 25, 1.6),
    anchor('hide.maintenance_bay', 'hiding', 74, 26, 1.6),
    anchor('hide.transit_structure', 'hiding', 46.25, 45, 1.6),
    anchor('blend.delivery_activity', 'blending', 25, 30, 2.2),
    anchor('blend.public_queue', 'blending', 53, 30, 2.2),
    anchor('objective.medkits', 'objective', 70, 25, 1.2, 'terminal.cache_locker'),
    anchor('objective.manifest', 'objective', 72, 25, 1.2, 'terminal.cache_locker'),
    anchor('camera.public_approach', 'camera', 60, 18, 0.8, 'camera.group.logistics'),
    anchor('camera.public_gate', 'camera', 61, 21, 0.8, 'camera.group.logistics'),
    anchor('camera.service_gate', 'camera', 72, 22.5, 0.8, 'camera.group.logistics'),
    anchor('camera.service_alley', 'camera', 60, 26, 0.8, 'camera.group.logistics'),
    anchor('audio.curfew.public', 'audio', 42, 30, 6, 'schedule.curfew'),
    anchor('interaction.safehouse.wait', 'interaction', 18, 47, 1.2, 'safehouse.wait'),
    anchor('interaction.safehouse.rest', 'interaction', 15, 47, 1.2, 'safehouse.rest'),
  ],
  occluders: buildingFootprints.map((footprint) => footprint.polygon),
  semanticMaskIds: [
    'mask.level0.walkable',
    'mask.level0.blocked',
    'mask.level0.occlusion',
    'mask.level0.interaction',
    'mask.level0.surveillance',
  ],
  artLayerIds: [
    'layer.level0.greybox.ground',
    'layer.level0.greybox.architecture',
    'layer.level0.greybox.semantic',
    'layer.level0.greybox.atmosphere',
  ],
};
